//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2021._01._04.ed.kodyue;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Kod kraju członkowskiego wspólnoty europejskiej
 * 
 * <p>Java class for TKodKrajuUE</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="TKodKrajuUE">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     <pattern value="[A-Z]{2}"/>
 *     <enumeration value="AT"/>
 *     <enumeration value="BE"/>
 *     <enumeration value="BG"/>
 *     <enumeration value="CY"/>
 *     <enumeration value="CZ"/>
 *     <enumeration value="DK"/>
 *     <enumeration value="DE"/>
 *     <enumeration value="EE"/>
 *     <enumeration value="EL"/>
 *     <enumeration value="ES"/>
 *     <enumeration value="FI"/>
 *     <enumeration value="FR"/>
 *     <enumeration value="GB"/>
 *     <enumeration value="HR"/>
 *     <enumeration value="HU"/>
 *     <enumeration value="IE"/>
 *     <enumeration value="IT"/>
 *     <enumeration value="LV"/>
 *     <enumeration value="LT"/>
 *     <enumeration value="LU"/>
 *     <enumeration value="MT"/>
 *     <enumeration value="NL"/>
 *     <enumeration value="PT"/>
 *     <enumeration value="RO"/>
 *     <enumeration value="SE"/>
 *     <enumeration value="SI"/>
 *     <enumeration value="SK"/>
 *     <enumeration value="XI"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "TKodKrajuUE", namespace = "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/01/04/eD/KodyUE/")
@XmlEnum
public enum TKodKrajuUE {


    /**
     * AUSTRIA
     * 
     */
    AT,

    /**
     * BELGIA
     * 
     */
    BE,

    /**
     * BUŁGARIA
     * 
     */
    BG,

    /**
     * CYPR
     * 
     */
    CY,

    /**
     * REPUBLIKA CZESKA
     * 
     */
    CZ,

    /**
     * DANIA
     * 
     */
    DK,

    /**
     * NIEMCY
     * 
     */
    DE,

    /**
     * ESTONIA
     * 
     */
    EE,

    /**
     * GRECJA
     * 
     */
    EL,

    /**
     * HISZPANIA
     * 
     */
    ES,

    /**
     * FINLANDIA
     * 
     */
    FI,

    /**
     * FRANCJA
     * 
     */
    FR,

    /**
     * WIELKA BRYTANIA
     * 
     */
    GB,

    /**
     * CHORWACJA
     * 
     */
    HR,

    /**
     * WĘGRY
     * 
     */
    HU,

    /**
     * IRLANDIA
     * 
     */
    IE,

    /**
     * WŁOCHY
     * 
     */
    IT,

    /**
     * ŁOTWA
     * 
     */
    LV,

    /**
     * LITWA
     * 
     */
    LT,

    /**
     * LUKSEMBURG
     * 
     */
    LU,

    /**
     * MALTA
     * 
     */
    MT,

    /**
     * HOLANDIA
     * 
     */
    NL,

    /**
     * PORTUGALIA
     * 
     */
    PT,

    /**
     * RUMUNIA
     * 
     */
    RO,

    /**
     * SZWECJA
     * 
     */
    SE,

    /**
     * SŁOWENIA
     * 
     */
    SI,

    /**
     * SŁOWACJA
     * 
     */
    SK,

    /**
     * IRLANDIA PÓŁNOCNA
     * 
     */
    XI;

    public String value() {
        return name();
    }

    public static TKodKrajuUE fromValue(String v) {
        return valueOf(v);
    }

}
