//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citd;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citd package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalacznikCITD }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITD }
     */
    public ZalacznikCITD createZalacznikCITD() {
        return new ZalacznikCITD();
    }

    /**
     * Create an instance of {@link ZalacznikCITD.PozycjeSzczegolowe }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITD.PozycjeSzczegolowe }
     */
    public ZalacznikCITD.PozycjeSzczegolowe createZalacznikCITDPozycjeSzczegolowe() {
        return new ZalacznikCITD.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekCITD }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITD }
     */
    public TNaglowekCITD createTNaglowekCITD() {
        return new TNaglowekCITD();
    }

    /**
     * Create an instance of {@link ZalacznikCITD.PozycjeSzczegolowe.PC }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITD.PozycjeSzczegolowe.PC }
     */
    public ZalacznikCITD.PozycjeSzczegolowe.PC createZalacznikCITDPozycjeSzczegolowePC() {
        return new ZalacznikCITD.PozycjeSzczegolowe.PC();
    }

    /**
     * Create an instance of {@link ZalacznikCITD.PozycjeSzczegolowe.PE }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITD.PozycjeSzczegolowe.PE }
     */
    public ZalacznikCITD.PozycjeSzczegolowe.PE createZalacznikCITDPozycjeSzczegolowePE() {
        return new ZalacznikCITD.PozycjeSzczegolowe.PE();
    }

    /**
     * Create an instance of {@link TNaglowekCITD.KodFormularza }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITD.KodFormularza }
     */
    public TNaglowekCITD.KodFormularza createTNaglowekCITDKodFormularza() {
        return new TNaglowekCITD.KodFormularza();
    }

    /**
     * Create an instance of {@link TNaglowekCITD.OkresOd }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITD.OkresOd }
     */
    public TNaglowekCITD.OkresOd createTNaglowekCITDOkresOd() {
        return new TNaglowekCITD.OkresOd();
    }

    /**
     * Create an instance of {@link TNaglowekCITD.OkresDo }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITD.OkresDo }
     */
    public TNaglowekCITD.OkresDo createTNaglowekCITDOkresDo() {
        return new TNaglowekCITD.OkresDo();
    }

}
