//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citd;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import pl.gov.crd.xml.schematy.dziedzinowe.mf._2023._09._06.ed.kodykrajow.TKodKraju;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Naglowek" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITD/}TNaglowek_CIT-D"/>
 *         <element name="PozycjeSzczegolowe">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="P_6" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                   <element name="P_8">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *                         <enumeration value="2"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="P_10">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *                         <enumeration value="1"/>
 *                         <enumeration value="2"/>
 *                         <enumeration value="3"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <sequence minOccurs="0">
 *                     <element name="P_21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                     <element name="P_C" maxOccurs="unbounded">
 *                       <complexType>
 *                         <complexContent>
 *                           <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             <sequence>
 *                               <element name="P_C22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                               <element name="P_C23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
 *                               <sequence>
 *                                 <element name="P_C24A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
 *                                 <element name="P_C25" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                                 <element name="P_C26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                                 <element name="P_C27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                                 <element name="P_C28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
 *                                 <element name="P_C29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
 *                                 <element name="P_C30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
 *                                 <element name="P_C31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
 *                                 <element name="P_C32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
 *                               </sequence>
 *                             </sequence>
 *                             <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
 *                           </restriction>
 *                         </complexContent>
 *                       </complexType>
 *                     </element>
 *                   </sequence>
 *                   <sequence minOccurs="0">
 *                     <element name="P_33" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_34" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_35" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_36" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_37" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_38" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_39" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_40" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_41" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_42" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_43" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_44" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_45" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_46" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                     <element name="P_47" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                   </sequence>
 *                   <element name="P_48" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
 *                   <sequence minOccurs="0">
 *                     <element name="P_49" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                     <element name="P_50" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                     <element name="P_E" maxOccurs="unbounded">
 *                       <complexType>
 *                         <complexContent>
 *                           <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             <sequence>
 *                               <element name="P_E51" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                               <element name="P_E52" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                               <sequence>
 *                                 <element name="P_E53" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrIdentyfikacjiPodatkowej"/>
 *                                 <element name="P_E54" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
 *                                 <element name="P_E55" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
 *                               </sequence>
 *                               <sequence>
 *                                 <element name="P_E56A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
 *                                 <element name="P_E57" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                                 <element name="P_E58" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                                 <element name="P_E59" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                                 <element name="P_E60" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
 *                                 <element name="P_E61" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
 *                                 <element name="P_E62" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
 *                                 <element name="P_E63" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
 *                                 <element name="P_E64" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
 *                               </sequence>
 *                             </sequence>
 *                             <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
 *                           </restriction>
 *                         </complexContent>
 *                       </complexType>
 *                     </element>
 *                   </sequence>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naglowek",
    "pozycjeSzczegolowe"
})
@XmlRootElement(name = "Zalacznik_CIT-D")
public class ZalacznikCITD {

    @XmlElement(name = "Naglowek", required = true)
    protected TNaglowekCITD naglowek;
    /**
     * Informacja o darowiznach, informacje o celach i publikacji, informacja podatnika (darczyńcy) korzystającego z odliczenia o przekazanych darowiznach
     * 
     */
    @XmlElement(name = "PozycjeSzczegolowe", required = true)
    protected PozycjeSzczegolowe pozycjeSzczegolowe;

    /**
     * Gets the value of the naglowek property.
     * 
     * @return
     *     possible object is
     *     {@link TNaglowekCITD }
     *     
     */
    public TNaglowekCITD getNaglowek() {
        return naglowek;
    }

    /**
     * Sets the value of the naglowek property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNaglowekCITD }
     *     
     */
    public void setNaglowek(TNaglowekCITD value) {
        this.naglowek = value;
    }

    /**
     * Informacja o darowiznach, informacje o celach i publikacji, informacja podatnika (darczyńcy) korzystającego z odliczenia o przekazanych darowiznach
     * 
     * @return
     *     possible object is
     *     {@link PozycjeSzczegolowe }
     *     
     */
    public PozycjeSzczegolowe getPozycjeSzczegolowe() {
        return pozycjeSzczegolowe;
    }

    /**
     * Sets the value of the pozycjeSzczegolowe property.
     * 
     * @param value
     *     allowed object is
     *     {@link PozycjeSzczegolowe }
     *     
     * @see #getPozycjeSzczegolowe()
     */
    public void setPozycjeSzczegolowe( PozycjeSzczegolowe value) {
        this.pozycjeSzczegolowe = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="P_6" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *         <element name="P_8">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}byte">
     *               <enumeration value="2"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="P_10">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}byte">
     *               <enumeration value="1"/>
     *               <enumeration value="2"/>
     *               <enumeration value="3"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <sequence minOccurs="0">
     *           <element name="P_21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *           <element name="P_C" maxOccurs="unbounded">
     *             <complexType>
     *               <complexContent>
     *                 <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   <sequence>
     *                     <element name="P_C22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *                     <element name="P_C23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
     *                     <sequence>
     *                       <element name="P_C24A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
     *                       <element name="P_C25" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                       <element name="P_C26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                       <element name="P_C27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                       <element name="P_C28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
     *                       <element name="P_C29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
     *                       <element name="P_C30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
     *                       <element name="P_C31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
     *                       <element name="P_C32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
     *                     </sequence>
     *                   </sequence>
     *                   <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
     *                 </restriction>
     *               </complexContent>
     *             </complexType>
     *           </element>
     *         </sequence>
     *         <sequence minOccurs="0">
     *           <element name="P_33" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_34" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_35" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_36" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_37" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_38" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_39" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_40" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_41" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_42" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_43" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_44" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_45" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_46" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *           <element name="P_47" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *         </sequence>
     *         <element name="P_48" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1" minOccurs="0"/>
     *         <sequence minOccurs="0">
     *           <element name="P_49" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *           <element name="P_50" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *           <element name="P_E" maxOccurs="unbounded">
     *             <complexType>
     *               <complexContent>
     *                 <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   <sequence>
     *                     <element name="P_E51" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *                     <element name="P_E52" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *                     <sequence>
     *                       <element name="P_E53" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrIdentyfikacjiPodatkowej"/>
     *                       <element name="P_E54" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
     *                       <element name="P_E55" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
     *                     </sequence>
     *                     <sequence>
     *                       <element name="P_E56A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
     *                       <element name="P_E57" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                       <element name="P_E58" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                       <element name="P_E59" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                       <element name="P_E60" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
     *                       <element name="P_E61" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
     *                       <element name="P_E62" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
     *                       <element name="P_E63" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
     *                       <element name="P_E64" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
     *                     </sequence>
     *                   </sequence>
     *                   <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
     *                 </restriction>
     *               </complexContent>
     *             </complexType>
     *           </element>
     *         </sequence>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p6",
        "p8",
        "p10",
        "p21",
        "pc",
        "p33",
        "p34",
        "p35",
        "p36",
        "p37",
        "p38",
        "p39",
        "p40",
        "p41",
        "p42",
        "p43",
        "p44",
        "p45",
        "p46",
        "p47",
        "p48",
        "p49",
        "p50",
        "pe"
    })
    public static class PozycjeSzczegolowe {

        /**
         * Nr formularza
         * 
         */
        @XmlElement(name = "P_6")
        protected Byte p6;
        /**
         * Informacja stanowi załącznik do zeznania
         * 
         */
        @XmlElement(name = "P_8")
        protected byte p8;
        /**
         * Rodzaj podatnika
         * 
         */
        @XmlElement(name = "P_10")
        protected byte p10;
        /**
         * Kwota ogółem otrzymanych darowizn
         * 
         */
        @XmlElement(name = "P_21")
        protected BigDecimal p21;
        /**
         * Dane darczyńcy
         * 
         */
        @XmlElement(name = "P_C")
        protected List<PC> pc;
        /**
         * Działalność charytatywna
         * 
         */
        @XmlElement(name = "P_33")
        protected Byte p33;
        /**
         * Pomoc ofiarom katastrof, klęsk żywiołowych, konfliktów zbrojnych i wojen w kraju i za granicą
         * 
         */
        @XmlElement(name = "P_34")
        protected Byte p34;
        /**
         * Pomoc społeczna, w tym pomoc rodzinom i osobom w trudnej sytuacji życiowej oraz wyrównywanie szans tych rodzin i osób
         * 
         */
        @XmlElement(name = "P_35")
        protected Byte p35;
        /**
         * Krajoznawstwo oraz wypoczynek dzieci i młodzieży
         * 
         */
        @XmlElement(name = "P_36")
        protected Byte p36;
        /**
         * Nauka, edukacja, oświata i wychowanie
         * 
         */
        @XmlElement(name = "P_37")
        protected Byte p37;
        /**
         * Działania na rzecz osób niepełnosprawnych
         * 
         */
        @XmlElement(name = "P_38")
        protected Byte p38;
        /**
         * Kultura, sztuka, ochrona dóbr kultury i tradycji
         * 
         */
        @XmlElement(name = "P_39")
        protected Byte p39;
        /**
         * Ekologia i ochrona zwierząt oraz ochrona dziedzictwa przyrodniczego
         * 
         */
        @XmlElement(name = "P_40")
        protected Byte p40;
        /**
         * Ochrona i promocja zdrowia
         * 
         */
        @XmlElement(name = "P_41")
        protected Byte p41;
        /**
         * Działalność wspomagająca rozwój gospodarczy, w tym rozwój przedsiębiorczości
         * 
         */
        @XmlElement(name = "P_42")
        protected Byte p42;
        /**
         * Upowszechnienie kultury fizycznej i sportu
         * 
         */
        @XmlElement(name = "P_43")
        protected Byte p43;
        /**
         * Ratownictwo i ochrona ludności
         * 
         */
        @XmlElement(name = "P_44")
        protected Byte p44;
        /**
         * Cele kultu religijnego
         * 
         */
        @XmlElement(name = "P_45")
        protected Byte p45;
        /**
         * Działalność charytatywno-opiekuńcza
         * 
         */
        @XmlElement(name = "P_46")
        protected Byte p46;
        /**
         * Pozostałe cele
         * 
         */
        @XmlElement(name = "P_47")
        protected Byte p47;
        /**
         * Podatnik udostępnił do publicznej wiadomości informacje na podstawie art. 18 ust. 1e pkt 2 ustawy
         * 
         */
        @XmlElement(name = "P_48")
        protected Byte p48;
        /**
         * Kwota przekazanej darowizny ogółem
         * 
         */
        @XmlElement(name = "P_49")
        protected BigDecimal p49;
        /**
         * Kwota odliczonej darowizny ogółem
         * 
         */
        @XmlElement(name = "P_50")
        protected BigDecimal p50;
        @XmlElement(name = "P_E")
        protected List<PE> pe;

        /**
         * Nr formularza
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP6() {
            return p6;
        }

        /**
         * Sets the value of the p6 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP6()
         */
        public void setP6(Byte value) {
            this.p6 = value;
        }

        /**
         * Informacja stanowi załącznik do zeznania
         * 
         */
        public byte getP8() {
            return p8;
        }

        /**
         * Sets the value of the p8 property.
         * 
         */
        public void setP8(byte value) {
            this.p8 = value;
        }

        /**
         * Rodzaj podatnika
         * 
         */
        public byte getP10() {
            return p10;
        }

        /**
         * Sets the value of the p10 property.
         * 
         */
        public void setP10(byte value) {
            this.p10 = value;
        }

        /**
         * Kwota ogółem otrzymanych darowizn
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP21() {
            return p21;
        }

        /**
         * Sets the value of the p21 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP21()
         */
        public void setP21(BigDecimal value) {
            this.p21 = value;
        }

        /**
         * Dane darczyńcy
         * 
         * Gets the value of the pc property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pc property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getPC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PC }
         * </p>
         * 
         * 
         * @return
         *     The value of the pc property.
         */
        public List<PC> getPC() {
            if (pc == null) {
                pc = new ArrayList<>();
            }
            return this.pc;
        }

        /**
         * Działalność charytatywna
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP33() {
            return p33;
        }

        /**
         * Sets the value of the p33 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP33()
         */
        public void setP33(Byte value) {
            this.p33 = value;
        }

        /**
         * Pomoc ofiarom katastrof, klęsk żywiołowych, konfliktów zbrojnych i wojen w kraju i za granicą
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP34() {
            return p34;
        }

        /**
         * Sets the value of the p34 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP34()
         */
        public void setP34(Byte value) {
            this.p34 = value;
        }

        /**
         * Pomoc społeczna, w tym pomoc rodzinom i osobom w trudnej sytuacji życiowej oraz wyrównywanie szans tych rodzin i osób
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP35() {
            return p35;
        }

        /**
         * Sets the value of the p35 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP35()
         */
        public void setP35(Byte value) {
            this.p35 = value;
        }

        /**
         * Krajoznawstwo oraz wypoczynek dzieci i młodzieży
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP36() {
            return p36;
        }

        /**
         * Sets the value of the p36 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP36()
         */
        public void setP36(Byte value) {
            this.p36 = value;
        }

        /**
         * Nauka, edukacja, oświata i wychowanie
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP37() {
            return p37;
        }

        /**
         * Sets the value of the p37 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP37()
         */
        public void setP37(Byte value) {
            this.p37 = value;
        }

        /**
         * Działania na rzecz osób niepełnosprawnych
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP38() {
            return p38;
        }

        /**
         * Sets the value of the p38 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP38()
         */
        public void setP38(Byte value) {
            this.p38 = value;
        }

        /**
         * Kultura, sztuka, ochrona dóbr kultury i tradycji
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP39() {
            return p39;
        }

        /**
         * Sets the value of the p39 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP39()
         */
        public void setP39(Byte value) {
            this.p39 = value;
        }

        /**
         * Ekologia i ochrona zwierząt oraz ochrona dziedzictwa przyrodniczego
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP40() {
            return p40;
        }

        /**
         * Sets the value of the p40 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP40()
         */
        public void setP40(Byte value) {
            this.p40 = value;
        }

        /**
         * Ochrona i promocja zdrowia
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP41() {
            return p41;
        }

        /**
         * Sets the value of the p41 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP41()
         */
        public void setP41(Byte value) {
            this.p41 = value;
        }

        /**
         * Działalność wspomagająca rozwój gospodarczy, w tym rozwój przedsiębiorczości
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP42() {
            return p42;
        }

        /**
         * Sets the value of the p42 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP42()
         */
        public void setP42(Byte value) {
            this.p42 = value;
        }

        /**
         * Upowszechnienie kultury fizycznej i sportu
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP43() {
            return p43;
        }

        /**
         * Sets the value of the p43 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP43()
         */
        public void setP43(Byte value) {
            this.p43 = value;
        }

        /**
         * Ratownictwo i ochrona ludności
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP44() {
            return p44;
        }

        /**
         * Sets the value of the p44 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP44()
         */
        public void setP44(Byte value) {
            this.p44 = value;
        }

        /**
         * Cele kultu religijnego
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP45() {
            return p45;
        }

        /**
         * Sets the value of the p45 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP45()
         */
        public void setP45(Byte value) {
            this.p45 = value;
        }

        /**
         * Działalność charytatywno-opiekuńcza
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP46() {
            return p46;
        }

        /**
         * Sets the value of the p46 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP46()
         */
        public void setP46(Byte value) {
            this.p46 = value;
        }

        /**
         * Pozostałe cele
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP47() {
            return p47;
        }

        /**
         * Sets the value of the p47 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP47()
         */
        public void setP47(Byte value) {
            this.p47 = value;
        }

        /**
         * Podatnik udostępnił do publicznej wiadomości informacje na podstawie art. 18 ust. 1e pkt 2 ustawy
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP48() {
            return p48;
        }

        /**
         * Sets the value of the p48 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP48()
         */
        public void setP48(Byte value) {
            this.p48 = value;
        }

        /**
         * Kwota przekazanej darowizny ogółem
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP49() {
            return p49;
        }

        /**
         * Sets the value of the p49 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP49()
         */
        public void setP49(BigDecimal value) {
            this.p49 = value;
        }

        /**
         * Kwota odliczonej darowizny ogółem
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP50() {
            return p50;
        }

        /**
         * Sets the value of the p50 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP50()
         */
        public void setP50(BigDecimal value) {
            this.p50 = value;
        }

        /**
         * Gets the value of the pe property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pe property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getPE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PE }
         * </p>
         * 
         * 
         * @return
         *     The value of the pe property.
         */
        public List<PE> getPE() {
            if (pe == null) {
                pe = new ArrayList<>();
            }
            return this.pe;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="P_C22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
         *         <element name="P_C23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
         *         <sequence>
         *           <element name="P_C24A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
         *           <element name="P_C25" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_C26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_C27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_C28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
         *           <element name="P_C29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
         *           <element name="P_C30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
         *           <element name="P_C31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
         *           <element name="P_C32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
         *         </sequence>
         *       </sequence>
         *       <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pc22",
            "pc23",
            "pc24A",
            "pc25",
            "pc26",
            "pc27",
            "pc28",
            "pc29",
            "pc30",
            "pc31",
            "pc32"
        })
        public static class PC {

            /**
             * Kwota darowizny
             * 
             */
            @XmlElement(name = "P_C22", required = true)
            protected BigDecimal pc22;
            /**
             * Nazwa pełna
             * 
             */
            @XmlElement(name = "P_C23", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc23;
            /**
             * Kraj
             * 
             */
            @XmlElement(name = "P_C24A", required = true)
            @XmlSchemaType(name = "normalizedString")
            protected TKodKraju pc24A;
            /**
             * Województwo
             * 
             */
            @XmlElement(name = "P_C25")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc25;
            /**
             * Powiat
             * 
             */
            @XmlElement(name = "P_C26")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc26;
            /**
             * Gmina
             * 
             */
            @XmlElement(name = "P_C27")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc27;
            /**
             * Ulica
             * 
             */
            @XmlElement(name = "P_C28")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc28;
            /**
             * Nr domu
             * 
             */
            @XmlElement(name = "P_C29")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc29;
            /**
             * Nr lokalu
             * 
             */
            @XmlElement(name = "P_C30")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc30;
            /**
             * Miejscowość
             * 
             */
            @XmlElement(name = "P_C31", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc31;
            /**
             * Kod pocztowy
             * 
             */
            @XmlElement(name = "P_C32")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pc32;
            @XmlAttribute(name = "typ", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String typ;

            /**
             * Kwota darowizny
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPC22() {
                return pc22;
            }

            /**
             * Sets the value of the pc22 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getPC22()
             */
            public void setPC22(BigDecimal value) {
                this.pc22 = value;
            }

            /**
             * Nazwa pełna
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC23() {
                return pc23;
            }

            /**
             * Sets the value of the pc23 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC23()
             */
            public void setPC23(String value) {
                this.pc23 = value;
            }

            /**
             * Kraj
             * 
             * @return
             *     possible object is
             *     {@link TKodKraju }
             *     
             */
            public TKodKraju getPC24A() {
                return pc24A;
            }

            /**
             * Sets the value of the pc24A property.
             * 
             * @param value
             *     allowed object is
             *     {@link TKodKraju }
             *     
             * @see #getPC24A()
             */
            public void setPC24A(TKodKraju value) {
                this.pc24A = value;
            }

            /**
             * Województwo
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC25() {
                return pc25;
            }

            /**
             * Sets the value of the pc25 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC25()
             */
            public void setPC25(String value) {
                this.pc25 = value;
            }

            /**
             * Powiat
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC26() {
                return pc26;
            }

            /**
             * Sets the value of the pc26 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC26()
             */
            public void setPC26(String value) {
                this.pc26 = value;
            }

            /**
             * Gmina
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC27() {
                return pc27;
            }

            /**
             * Sets the value of the pc27 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC27()
             */
            public void setPC27(String value) {
                this.pc27 = value;
            }

            /**
             * Ulica
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC28() {
                return pc28;
            }

            /**
             * Sets the value of the pc28 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC28()
             */
            public void setPC28(String value) {
                this.pc28 = value;
            }

            /**
             * Nr domu
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC29() {
                return pc29;
            }

            /**
             * Sets the value of the pc29 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC29()
             */
            public void setPC29(String value) {
                this.pc29 = value;
            }

            /**
             * Nr lokalu
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC30() {
                return pc30;
            }

            /**
             * Sets the value of the pc30 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC30()
             */
            public void setPC30(String value) {
                this.pc30 = value;
            }

            /**
             * Miejscowość
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC31() {
                return pc31;
            }

            /**
             * Sets the value of the pc31 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC31()
             */
            public void setPC31(String value) {
                this.pc31 = value;
            }

            /**
             * Kod pocztowy
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPC32() {
                return pc32;
            }

            /**
             * Sets the value of the pc32 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPC32()
             */
            public void setPC32(String value) {
                this.pc32 = value;
            }

            /**
             * Gets the value of the typ property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTyp() {
                if (typ == null) {
                    return "G";
                } else {
                    return typ;
                }
            }

            /**
             * Sets the value of the typ property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTyp(String value) {
                this.typ = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="P_E51" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
         *         <element name="P_E52" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
         *         <sequence>
         *           <element name="P_E53" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrIdentyfikacjiPodatkowej"/>
         *           <element name="P_E54" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
         *           <element name="P_E55" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
         *         </sequence>
         *         <sequence>
         *           <element name="P_E56A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
         *           <element name="P_E57" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_E58" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_E59" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_E60" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
         *           <element name="P_E61" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
         *           <element name="P_E62" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
         *           <element name="P_E63" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
         *           <element name="P_E64" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
         *         </sequence>
         *       </sequence>
         *       <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pe51",
            "pe52",
            "pe53",
            "pe54",
            "pe55",
            "pe56A",
            "pe57",
            "pe58",
            "pe59",
            "pe60",
            "pe61",
            "pe62",
            "pe63",
            "pe64"
        })
        public static class PE {

            /**
             * Kwota przekazanej darowizny
             * 
             */
            @XmlElement(name = "P_E51", required = true)
            protected BigDecimal pe51;
            /**
             * Kwota odliczonej darowizny
             * 
             */
            @XmlElement(name = "P_E52", required = true)
            protected BigDecimal pe52;
            /**
             * Identyfikator podatkowy NIP lub numer uzyskany w innym niż Rzeczpospolita Polska państwie członkowskim Unii Europejskiej lub innym państwie należącym do Europejskiego Obszaru Gospodarczego, w którym obdarowany ma siedzibę, służący dla celów podatkowych identyfikacji
             * 
             */
            @XmlElement(name = "P_E53", required = true)
            protected String pe53;
            /**
             * Kod kraju numeru identyfikacji podatkowej
             * 
             */
            @XmlElement(name = "P_E54", required = true)
            @XmlSchemaType(name = "normalizedString")
            protected TKodKraju pe54;
            /**
             * Nazwa pełna
             * 
             */
            @XmlElement(name = "P_E55", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe55;
            /**
             * Kraj
             * 
             */
            @XmlElement(name = "P_E56A", required = true)
            @XmlSchemaType(name = "normalizedString")
            protected TKodKraju pe56A;
            /**
             * Województwo
             * 
             */
            @XmlElement(name = "P_E57")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe57;
            /**
             * Powiat
             * 
             */
            @XmlElement(name = "P_E58")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe58;
            /**
             * Gmina
             * 
             */
            @XmlElement(name = "P_E59")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe59;
            /**
             * Ulica
             * 
             */
            @XmlElement(name = "P_E60")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe60;
            /**
             * Nr domu
             * 
             */
            @XmlElement(name = "P_E61")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe61;
            /**
             * Nr lokalu
             * 
             */
            @XmlElement(name = "P_E62")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe62;
            /**
             * Miejscowość
             * 
             */
            @XmlElement(name = "P_E63", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe63;
            /**
             * Kod pocztowy
             * 
             */
            @XmlElement(name = "P_E64")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pe64;
            @XmlAttribute(name = "typ", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String typ;

            /**
             * Kwota przekazanej darowizny
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPE51() {
                return pe51;
            }

            /**
             * Sets the value of the pe51 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getPE51()
             */
            public void setPE51(BigDecimal value) {
                this.pe51 = value;
            }

            /**
             * Kwota odliczonej darowizny
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPE52() {
                return pe52;
            }

            /**
             * Sets the value of the pe52 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getPE52()
             */
            public void setPE52(BigDecimal value) {
                this.pe52 = value;
            }

            /**
             * Identyfikator podatkowy NIP lub numer uzyskany w innym niż Rzeczpospolita Polska państwie członkowskim Unii Europejskiej lub innym państwie należącym do Europejskiego Obszaru Gospodarczego, w którym obdarowany ma siedzibę, służący dla celów podatkowych identyfikacji
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE53() {
                return pe53;
            }

            /**
             * Sets the value of the pe53 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE53()
             */
            public void setPE53(String value) {
                this.pe53 = value;
            }

            /**
             * Kod kraju numeru identyfikacji podatkowej
             * 
             * @return
             *     possible object is
             *     {@link TKodKraju }
             *     
             */
            public TKodKraju getPE54() {
                return pe54;
            }

            /**
             * Sets the value of the pe54 property.
             * 
             * @param value
             *     allowed object is
             *     {@link TKodKraju }
             *     
             * @see #getPE54()
             */
            public void setPE54(TKodKraju value) {
                this.pe54 = value;
            }

            /**
             * Nazwa pełna
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE55() {
                return pe55;
            }

            /**
             * Sets the value of the pe55 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE55()
             */
            public void setPE55(String value) {
                this.pe55 = value;
            }

            /**
             * Kraj
             * 
             * @return
             *     possible object is
             *     {@link TKodKraju }
             *     
             */
            public TKodKraju getPE56A() {
                return pe56A;
            }

            /**
             * Sets the value of the pe56A property.
             * 
             * @param value
             *     allowed object is
             *     {@link TKodKraju }
             *     
             * @see #getPE56A()
             */
            public void setPE56A(TKodKraju value) {
                this.pe56A = value;
            }

            /**
             * Województwo
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE57() {
                return pe57;
            }

            /**
             * Sets the value of the pe57 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE57()
             */
            public void setPE57(String value) {
                this.pe57 = value;
            }

            /**
             * Powiat
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE58() {
                return pe58;
            }

            /**
             * Sets the value of the pe58 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE58()
             */
            public void setPE58(String value) {
                this.pe58 = value;
            }

            /**
             * Gmina
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE59() {
                return pe59;
            }

            /**
             * Sets the value of the pe59 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE59()
             */
            public void setPE59(String value) {
                this.pe59 = value;
            }

            /**
             * Ulica
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE60() {
                return pe60;
            }

            /**
             * Sets the value of the pe60 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE60()
             */
            public void setPE60(String value) {
                this.pe60 = value;
            }

            /**
             * Nr domu
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE61() {
                return pe61;
            }

            /**
             * Sets the value of the pe61 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE61()
             */
            public void setPE61(String value) {
                this.pe61 = value;
            }

            /**
             * Nr lokalu
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE62() {
                return pe62;
            }

            /**
             * Sets the value of the pe62 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE62()
             */
            public void setPE62(String value) {
                this.pe62 = value;
            }

            /**
             * Miejscowość
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE63() {
                return pe63;
            }

            /**
             * Sets the value of the pe63 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE63()
             */
            public void setPE63(String value) {
                this.pe63 = value;
            }

            /**
             * Kod pocztowy
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPE64() {
                return pe64;
            }

            /**
             * Sets the value of the pe64 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPE64()
             */
            public void setPE64(String value) {
                this.pe64 = value;
            }

            /**
             * Gets the value of the typ property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTyp() {
                if (typ == null) {
                    return "G";
                } else {
                    return typ;
                }
            }

            /**
             * Sets the value of the typ property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTyp(String value) {
                this.typ = value;
            }

        }

    }

}
