logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          EnumType: trace
        orm:
          jdbc:
            bind: trace
server:
  port: 8080

databases:
  main:
    datasource:
      url: jdbc:postgresql://jan-ksiegowy.postgres.database.azure.com/postgres
      username: postgres
      password: Sylwia70
      hikari:
        schema: jan
        poolName: mainDataSource
    packages: pl.janksiegowy
    liquibase:
      enabled: true
      changeLog: classpath:db/changelog-main.yaml
  tenant:
    datasource:
      url-prefix: jdbc:postgresql://jan-ksiegowy.postgres.database.azure.com/
    cache:
      maximumSize: 2
      expireAfterAccess: 10
    liquibase:
      changeLog: classpath:db/changelog-tenant.yaml
  company:
    liquibase:
      changelog: classpath:db/changelog-company.yaml


azure:
  files:
    migration:
      sas: oFmTmfXSG5GSEqXURxN8MIoMfLnH%2BBU%2B3RcGwT%2Fyz60%3D
      url: https://janksiegowy.file.core.windows.net/migration