
spring:
  application:
    name: Jan Księgowy 2.3
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  cloud:
    azure:
      compatibility-verifier:
        enabled: false
