--liquibase formatted sql
--changeset piotrkorniak:102

CREATE TABLE USERS (
    ID UUID PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD TEXT NOT NULL,
    TENANT_ID UUID NOT NULL,
    ENABLED BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT now(),

    UNIQUE (TENANT_ID, USERNAME),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(ID)
);