//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citip;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citip package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citip
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalacznikCITIP }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITIP }
     */
    public ZalacznikCITIP createZalacznikCITIP() {
        return new ZalacznikCITIP();
    }

    /**
     * Create an instance of {@link ZalacznikCITIP.PozycjeSzczegolowe }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITIP.PozycjeSzczegolowe }
     */
    public ZalacznikCITIP.PozycjeSzczegolowe createZalacznikCITIPPozycjeSzczegolowe() {
        return new ZalacznikCITIP.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekCITIP }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITIP }
     */
    public TNaglowekCITIP createTNaglowekCITIP() {
        return new TNaglowekCITIP();
    }

    /**
     * Create an instance of {@link ZalacznikCITIP.PozycjeSzczegolowe.PG }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITIP.PozycjeSzczegolowe.PG }
     */
    public ZalacznikCITIP.PozycjeSzczegolowe.PG createZalacznikCITIPPozycjeSzczegolowePG() {
        return new ZalacznikCITIP.PozycjeSzczegolowe.PG();
    }

    /**
     * Create an instance of {@link TNaglowekCITIP.KodFormularza }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITIP.KodFormularza }
     */
    public TNaglowekCITIP.KodFormularza createTNaglowekCITIPKodFormularza() {
        return new TNaglowekCITIP.KodFormularza();
    }

    /**
     * Create an instance of {@link TNaglowekCITIP.OkresOd }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITIP.OkresOd }
     */
    public TNaglowekCITIP.OkresOd createTNaglowekCITIPOkresOd() {
        return new TNaglowekCITIP.OkresOd();
    }

    /**
     * Create an instance of {@link TNaglowekCITIP.OkresDo }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITIP.OkresDo }
     */
    public TNaglowekCITIP.OkresDo createTNaglowekCITIPOkresDo() {
        return new TNaglowekCITIP.OkresDo();
    }

}
