//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


@jakarta.xml.bind.annotation.XmlSchema(
        namespace = "http://www.w3.org/1999/XSL/Transform",
        elementFormDefault= XmlNsForm.QUALIFIED,

        xmlns= {
                @XmlNs( prefix = "xsl", namespaceURI = "http://www.w3.org/1999/XSL/Transform")
        }
)

package pl.janksiegowy.backend.shared.style;

import jakarta.xml.bind.annotation.XmlNs;
import jakarta.xml.bind.annotation.XmlNsForm;