--liquibase formatted sql
--changeset piotrkorniak:3

CREATE TABLE SETTLEMENTS (
     DOCUMENT_ID UUID,

     ENTITY_ID BIGINT,
     PERIOD_ID VARCHAR(7),

     TYPE CHAR(1),
     KIND CHAR(1),

     NUMBER VARCHAR(32),

     DATE DATE NOT NULL,
     DUE DATE NOT NULL,

     DT DECIMAL(12,2) NOT NULL,
     CT DECIMAL(12,2) NOT NULL,

     FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ID),
     UNIQUE( DOCUMENT_ID)

);

CREATE TABLE REGISTERS (
       ID UUID,
       TYPE CHAR(1) NOT NULL,
       KIND CHAR(2) NOT NULL,
       CODE VARCHAR(16),
       NAME VARCHAR(64),


       PRIMARY KEY (ID)
);


CREATE TABLE INVOICES (
      ID UUID,
      DATE DATE NOT NULL,
      METRIC_ID DATE,
      TYPE CHAR(1) NOT NULL,
      VAT_REGISTER_ID UUID REFERENCES REGISTERS(ID),

      SUB_TOTAL DECIMAL(12,2) NOT NULL,
      TAX_TOTAL DECIMAL(12,2) NOT NULL,

      FOREIGN KEY (METRIC_ID) REFERENCES METRICS(ID),


      PRIMARY KEY (ID)

);
