--liquibase formatted sql
--changeset piotrkorniak:8

CREATE TABLE PAYMENTS (
    ID UUID,
    TYPE CHAR(1) NOT NULL,
    DESCRIPTION VARCHAR( 256),
    REGISTER_ID UUID REFERENCES REGISTERS(ID),

    PRIMARY KEY (ID)

);

CREATE TABLE CLEARINGS (
    RECEIVABLE_ID UUID,
    PAYABLE_ID UUID,

    DATE DATE NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,

    FOREIGN KEY (RECEIVABLE_ID) REFERENCES SETTLEMENTS(DOCUMENT_ID),
    FOREIGN KEY (PAYABLE_ID) REFERENCES SETTLEMENTS(DOCUMENT_ID),

    PRIMARY KEY (RECEIVABLE_ID, PAYABLE_ID)
);