--liquibase formatted sql
--changeset piotrkorniak:09

CREATE TABLE NUMERATORS (
	ID UUID,
	CODE VARCHAR(32),
	NAME VARCHAR(128),
	MASK VARCHAR(32),
	TYPE VARCHAR(1) NOT NULL,
    TYPED BOOLEAN,

	PRIMARY KEY (ID)
);

CREATE TABLE COUNTERS (
    ID UUID,
    NUMERATOR_ID UUID REFERENCES NUMERATORS(ID),
    MONTH INTEGER,
    YEAR INTEGER,
    TYPE VARCHAR(9),
    VALUES BIGINT,
    VERSION BIGINT,

    PRIMARY KEY (ID)
);