--liquibase formatted sql
--changeset piotrkorniak:13

CREATE TABLE DECREES (
    ID UUID,

    PERIOD_ID VARCHAR(7),
    REGISTER_ID UUID,

    DATE DATE NOT NULL,
    TYPE CHAR(1),

    NUMBER VARCHAR(32),
    DOCUMENT VARCHAR(96),

    DT DECIMAL(12,2) NOT NULL,
    CT DECIMAL(12,2) NOT NULL,

    FOREIGN KEY (PERIOD_ID) REFERENCES PERIODS(ID),
    FOREIGN KEY (REGISTER_ID) REFERENCES REGISTERS(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE DECREES_LINES (
    ID UUID,
    DECREE_ID UUID,
    NO INT,

    SIDE CHAR(1),
    ACCOUNT_ID UUID,
    VALUE DECIMAL(12,2) NOT NULL,
    DESCRIPTION VARCHAR(96),

    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY (DECREE_ID) REFERENCES DECREES(ID),
    PRIMARY KEY (ID)
);