--liquibase formatted sql
--changeset piotrkorniak:22

ALTER TABLE PAYSLIPS_LINES RENAME COLUMN ITEM_CODE TO WAGE_INDICATOR_CODE;
ALTER TABLE PAYSLIPS_LINES DROP CONSTRAINT IF EXISTS payslips_lines_pkey;
ALTER TABLE PAYSLIPS_LINES DROP COLUMN IF EXISTS ID;

-- 4️⃣ Ustawienie nowego klucza głównego
ALTER TABLE PAYSLIPS_LINES ADD PRIMARY KEY (PAYSLIP_ID, WAGE_INDICATOR_CODE);

ALTER TABLE PAYSLIPS_LINES RENAME TO PAYSLIPS_ELEMENTS;
