--liquibase formatted sql
--changeset piotrkorniak:27

ALTER TABLE REGISTERS
    ADD ACCOUNT_NUMBER VARCHAR(10);

ALTER TABLE SETTLEMENTS
    ADD DECREE_ID UUID;

ALTER TABLE SETTLEMENTS
    ADD FOREIGN KEY (DECREE_ID) REFERENCES DECREES(ID);
