--liquibase formatted sql
--changeset piotrkorniak:30

CREATE TABLE BILLING_GROUPS (

    ID UUID PRIMARY KEY,
    NUMBER VARCHAR(20),
    NAME VARCHAR(255),
    PERIOD_ID VARCHAR(7) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'NEW',
    BILLING_TYPE_MASK BIGINT NOT NULL DEFAULT 0

);