--liquibase formatted sql
--changeset piotrkorniak:31

CREATE TABLE CONTRACTS (
    ID UUID,

    ENTITY_ID BIGINT,

    TYPE CHAR (1) NOT NULL,
    BEGIN DATE,
    "end" DATE,
    NUMBER VARCHAR(32),
    SALARY DECIMAL(12,2) NOT NULL,

    PRIMARY KEY (ID)
);


CREATE TABLE PAYSLIPS (
    ID UUID,
    TYPE CHAR(1) NOT NULL,

    GROSS DECIMAL(12,2) NOT NULL,
    INSURANCE_EMPLOYEE DECIMAL(12,2) NOT NULL,
    INSURANCE_EMPLOYER DECIMAL(12,2) NOT NULL,
    INSURANCE_HEALTH DECIMAL(12,2) NOT NULL,
    TAX_ADVANCE DECIMAL(12,2) NOT NULL,

    PRIMARY KEY (ID)
);
