--liquibase formatted sql
--changeset piotrkorniak:31

CREATE TABLE BILLING_GROUPS_LINES (

    ID UUID PRIMARY KEY,
    GROUP_ID UUID,
    PERIOD_ID VARCHAR(7) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'NEW',
    BILLING_TYPE BIGINT NOT NULL DEFAULT 0

);