--liquibase formatted sql
--changeset piotrkorniak:44

ALTER TABLE PAYSLIPS
    DROP COLUMN TYPE,
    DROP COLUMN GROSS,
    DROP COLUMN INSURANCE_EMPLOYEE,
    DROP COLUMN INSURANCE_EMPLOYER,
    DROP COLUMN TAX_ADVANCE,
    ADD CONTRACT_ID UUID;
