--liquibase formatted sql
--changeset piotrkorniak:40

CREATE TABLE SHARES (
    ID UUID,
    TYPE CHAR(1) NOT NULL,
    EQUITY DECIMAL(5,2) NOT NULL,

    PRIMARY KEY (ID)
);

ALTER TABLE TEMPLATES_LINES
    DROP COLUMN REGISTER_TYPE;

ALTER TABLE PAYMENTS
    ADD DESCRIPTION VARCHAR( 256);

ALTER TABLE SETTLEMENTS
    DROP COLUMN DECREE_ID;