//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.12 at 11:04:52 AM CET 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2021._06._09.ed.definicjetypy;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Zestaw danych identyfikacyjnych dla osoby fizycznej zagranicznej
 * 
 * &lt;p&gt;Java class for TIdentyfikatorOsobyFizycznejZagranicznej complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="TIdentyfikatorOsobyFizycznejZagranicznej"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="ImiePierwsze" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TImie"/&amp;gt;
 *         &amp;lt;element name="Nazwisko" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TNazwisko"/&amp;gt;
 *         &amp;lt;element name="DataUrodzenia" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TData"/&amp;gt;
 *         &amp;lt;element name="MiejsceUrodzenia" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TMiejscowosc"/&amp;gt;
 *         &amp;lt;element name="ImieOjca" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TImie" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ImieMatki" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TImie" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="NIP" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TNrNIP" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TIdentyfikatorOsobyFizycznejZagranicznej", propOrder = {
    "imiePierwsze",
    "nazwisko",
    "dataUrodzenia",
    "miejsceUrodzenia",
    "imieOjca",
    "imieMatki",
    "nip"
})
public class TIdentyfikatorOsobyFizycznejZagranicznej {

    @XmlElement(name = "ImiePierwsze", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String imiePierwsze;
    @XmlElement(name = "Nazwisko", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nazwisko;
    @XmlElement(name = "DataUrodzenia", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataUrodzenia;
    @XmlElement(name = "MiejsceUrodzenia", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String miejsceUrodzenia;
    @XmlElement(name = "ImieOjca")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String imieOjca;
    @XmlElement(name = "ImieMatki")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String imieMatki;
    @XmlElement(name = "NIP")
    protected String nip;

    /**
     * Gets the value of the imiePierwsze property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImiePierwsze() {
        return imiePierwsze;
    }

    /**
     * Sets the value of the imiePierwsze property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImiePierwsze(String value) {
        this.imiePierwsze = value;
    }

    /**
     * Gets the value of the nazwisko property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwisko() {
        return nazwisko;
    }

    /**
     * Sets the value of the nazwisko property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwisko(String value) {
        this.nazwisko = value;
    }

    /**
     * Gets the value of the dataUrodzenia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataUrodzenia() {
        return dataUrodzenia;
    }

    /**
     * Sets the value of the dataUrodzenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataUrodzenia(XMLGregorianCalendar value) {
        this.dataUrodzenia = value;
    }

    /**
     * Gets the value of the miejsceUrodzenia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiejsceUrodzenia() {
        return miejsceUrodzenia;
    }

    /**
     * Sets the value of the miejsceUrodzenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiejsceUrodzenia(String value) {
        this.miejsceUrodzenia = value;
    }

    /**
     * Gets the value of the imieOjca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImieOjca() {
        return imieOjca;
    }

    /**
     * Sets the value of the imieOjca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImieOjca(String value) {
        this.imieOjca = value;
    }

    /**
     * Gets the value of the imieMatki property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImieMatki() {
        return imieMatki;
    }

    /**
     * Sets the value of the imieMatki property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImieMatki(String value) {
        this.imieMatki = value;
    }

    /**
     * Gets the value of the nip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIP() {
        return nip;
    }

    /**
     * Sets the value of the nip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIP(String value) {
        this.nip = value;
    }

}
