//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.wzor._2023._06._29._12648;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.wzor._2023._06._29._12648 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.wzor._2023._06._29._12648
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Faktura_FA_2 }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2 }
     */
    public Faktura_FA_2 createFaktura() {
        return new Faktura_FA_2();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Stopka }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Stopka }
     */
    public Faktura_FA_2.Stopka createFakturaStopka() {
        return new Faktura_FA_2.Stopka();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa }
     */
    public Faktura_FA_2.Fa createFakturaFa() {
        return new Faktura_FA_2.Fa();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Zamowienie }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Zamowienie }
     */
    public Faktura_FA_2.Fa.Zamowienie createFakturaFaZamowienie() {
        return new Faktura_FA_2.Fa.Zamowienie();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji }
     */
    public Faktura_FA_2.Fa.WarunkiTransakcji createFakturaFaWarunkiTransakcji() {
        return new Faktura_FA_2.Fa.WarunkiTransakcji();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji.Transport }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji.Transport }
     */
    public Faktura_FA_2.Fa.WarunkiTransakcji.Transport createFakturaFaWarunkiTransakcjiTransport() {
        return new Faktura_FA_2.Fa.WarunkiTransakcji.Transport();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Platnosc }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Platnosc }
     */
    public Faktura_FA_2.Fa.Platnosc createFakturaFaPlatnosc() {
        return new Faktura_FA_2.Fa.Platnosc();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Rozliczenie }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Rozliczenie }
     */
    public Faktura_FA_2.Fa.Rozliczenie createFakturaFaRozliczenie() {
        return new Faktura_FA_2.Fa.Rozliczenie();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Adnotacje }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Adnotacje }
     */
    public Faktura_FA_2.Fa.Adnotacje createFakturaFaAdnotacje() {
        return new Faktura_FA_2.Fa.Adnotacje();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Adnotacje.NoweSrodkiTransportu }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Adnotacje.NoweSrodkiTransportu }
     */
    public Faktura_FA_2.Fa.Adnotacje.NoweSrodkiTransportu createFakturaFaAdnotacjeNoweSrodkiTransportu() {
        return new Faktura_FA_2.Fa.Adnotacje.NoweSrodkiTransportu();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.PodmiotUpowazniony }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.PodmiotUpowazniony }
     */
    public Faktura_FA_2.PodmiotUpowazniony createFakturaPodmiotUpowazniony() {
        return new Faktura_FA_2.PodmiotUpowazniony();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Podmiot3 }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Podmiot3 }
     */
    public Faktura_FA_2.Podmiot3 createFakturaPodmiot3() {
        return new Faktura_FA_2.Podmiot3();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Podmiot2 }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Podmiot2 }
     */
    public Faktura_FA_2.Podmiot2 createFakturaPodmiot2() {
        return new Faktura_FA_2.Podmiot2();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Podmiot1 }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Podmiot1 }
     */
    public Faktura_FA_2.Podmiot1 createFakturaPodmiot1() {
        return new Faktura_FA_2.Podmiot1();
    }

    /**
     * Create an instance of {@link TNaglowek }
     * 
     * @return
     *     the new instance of {@link TNaglowek }
     */
    public TNaglowek createTNaglowek() {
        return new TNaglowek();
    }

    /**
     * Create an instance of {@link TAdres }
     * 
     * @return
     *     the new instance of {@link TAdres }
     */
    public TAdres createTAdres() {
        return new TAdres();
    }

    /**
     * Create an instance of {@link TKluczWartosc }
     * 
     * @return
     *     the new instance of {@link TKluczWartosc }
     */
    public TKluczWartosc createTKluczWartosc() {
        return new TKluczWartosc();
    }

    /**
     * Create an instance of {@link TRachunekBankowy }
     * 
     * @return
     *     the new instance of {@link TRachunekBankowy }
     */
    public TRachunekBankowy createTRachunekBankowy() {
        return new TRachunekBankowy();
    }

    /**
     * Create an instance of {@link TPodmiot1 }
     * 
     * @return
     *     the new instance of {@link TPodmiot1 }
     */
    public TPodmiot1 createTPodmiot1() {
        return new TPodmiot1();
    }

    /**
     * Create an instance of {@link TPodmiot2 }
     * 
     * @return
     *     the new instance of {@link TPodmiot2 }
     */
    public TPodmiot2 createTPodmiot2() {
        return new TPodmiot2();
    }

    /**
     * Create an instance of {@link TPodmiot3 }
     * 
     * @return
     *     the new instance of {@link TPodmiot3 }
     */
    public TPodmiot3 createTPodmiot3() {
        return new TPodmiot3();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Stopka.Informacje }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Stopka.Informacje }
     */
    public Faktura_FA_2.Stopka.Informacje createFakturaStopkaInformacje() {
        return new Faktura_FA_2.Stopka.Informacje();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Stopka.Rejestry }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Stopka.Rejestry }
     */
    public Faktura_FA_2.Stopka.Rejestry createFakturaStopkaRejestry() {
        return new Faktura_FA_2.Stopka.Rejestry();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.OkresFa }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.OkresFa }
     */
    public Faktura_FA_2.Fa.OkresFa createFakturaFaOkresFa() {
        return new Faktura_FA_2.Fa.OkresFa();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.DaneFaKorygowanej }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.DaneFaKorygowanej }
     */
    public Faktura_FA_2.Fa.DaneFaKorygowanej createFakturaFaDaneFaKorygowanej() {
        return new Faktura_FA_2.Fa.DaneFaKorygowanej();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Podmiot1K }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Podmiot1K }
     */
    public Faktura_FA_2.Fa.Podmiot1K createFakturaFaPodmiot1K() {
        return new Faktura_FA_2.Fa.Podmiot1K();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Podmiot2K }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Podmiot2K }
     */
    public Faktura_FA_2.Fa.Podmiot2K createFakturaFaPodmiot2K() {
        return new Faktura_FA_2.Fa.Podmiot2K();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.ZaliczkaCzesciowa }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.ZaliczkaCzesciowa }
     */
    public Faktura_FA_2.Fa.ZaliczkaCzesciowa createFakturaFaZaliczkaCzesciowa() {
        return new Faktura_FA_2.Fa.ZaliczkaCzesciowa();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.FakturaZaliczkowa }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.FakturaZaliczkowa }
     */
    public Faktura_FA_2.Fa.FakturaZaliczkowa createFakturaFaFakturaZaliczkowa() {
        return new Faktura_FA_2.Fa.FakturaZaliczkowa();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.FaWiersz }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.FaWiersz }
     */
    public Faktura_FA_2.Fa.FaWiersz createFakturaFaFaWiersz() {
        return new Faktura_FA_2.Fa.FaWiersz();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Zamowienie.ZamowienieWiersz }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Zamowienie.ZamowienieWiersz }
     */
    public Faktura_FA_2.Fa.Zamowienie.ZamowienieWiersz createFakturaFaZamowienieZamowienieWiersz() {
        return new Faktura_FA_2.Fa.Zamowienie.ZamowienieWiersz();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji.Umowy }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji.Umowy }
     */
    public Faktura_FA_2.Fa.WarunkiTransakcji.Umowy createFakturaFaWarunkiTransakcjiUmowy() {
        return new Faktura_FA_2.Fa.WarunkiTransakcji.Umowy();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji.Zamowienia }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji.Zamowienia }
     */
    public Faktura_FA_2.Fa.WarunkiTransakcji.Zamowienia createFakturaFaWarunkiTransakcjiZamowienia() {
        return new Faktura_FA_2.Fa.WarunkiTransakcji.Zamowienia();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji.Transport.Przewoznik }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.WarunkiTransakcji.Transport.Przewoznik }
     */
    public Faktura_FA_2.Fa.WarunkiTransakcji.Transport.Przewoznik createFakturaFaWarunkiTransakcjiTransportPrzewoznik() {
        return new Faktura_FA_2.Fa.WarunkiTransakcji.Transport.Przewoznik();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Platnosc.ZaplataCzesciowa }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Platnosc.ZaplataCzesciowa }
     */
    public Faktura_FA_2.Fa.Platnosc.ZaplataCzesciowa createFakturaFaPlatnoscZaplataCzesciowa() {
        return new Faktura_FA_2.Fa.Platnosc.ZaplataCzesciowa();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Platnosc.TerminPlatnosci }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Platnosc.TerminPlatnosci }
     */
    public Faktura_FA_2.Fa.Platnosc.TerminPlatnosci createFakturaFaPlatnoscTerminPlatnosci() {
        return new Faktura_FA_2.Fa.Platnosc.TerminPlatnosci();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Platnosc.Skonto }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Platnosc.Skonto }
     */
    public Faktura_FA_2.Fa.Platnosc.Skonto createFakturaFaPlatnoscSkonto() {
        return new Faktura_FA_2.Fa.Platnosc.Skonto();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Rozliczenie.Obciazenia }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Rozliczenie.Obciazenia }
     */
    public Faktura_FA_2.Fa.Rozliczenie.Obciazenia createFakturaFaRozliczenieObciazenia() {
        return new Faktura_FA_2.Fa.Rozliczenie.Obciazenia();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Rozliczenie.Odliczenia }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Rozliczenie.Odliczenia }
     */
    public Faktura_FA_2.Fa.Rozliczenie.Odliczenia createFakturaFaRozliczenieOdliczenia() {
        return new Faktura_FA_2.Fa.Rozliczenie.Odliczenia();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Adnotacje.Zwolnienie }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Adnotacje.Zwolnienie }
     */
    public Faktura_FA_2.Fa.Adnotacje.Zwolnienie createFakturaFaAdnotacjeZwolnienie() {
        return new Faktura_FA_2.Fa.Adnotacje.Zwolnienie();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Adnotacje.PMarzy }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Adnotacje.PMarzy }
     */
    public Faktura_FA_2.Fa.Adnotacje.PMarzy createFakturaFaAdnotacjePMarzy() {
        return new Faktura_FA_2.Fa.Adnotacje.PMarzy();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu }
     */
    public Faktura_FA_2.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu createFakturaFaAdnotacjeNoweSrodkiTransportuNowySrodekTransportu() {
        return new Faktura_FA_2.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.PodmiotUpowazniony.DaneKontaktowe }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.PodmiotUpowazniony.DaneKontaktowe }
     */
    public Faktura_FA_2.PodmiotUpowazniony.DaneKontaktowe createFakturaPodmiotUpowaznionyDaneKontaktowe() {
        return new Faktura_FA_2.PodmiotUpowazniony.DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Podmiot3 .DaneKontaktowe }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Podmiot3 .DaneKontaktowe }
     */
    public Faktura_FA_2.Podmiot3 .DaneKontaktowe createFakturaPodmiot3DaneKontaktowe() {
        return new Faktura_FA_2.Podmiot3 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Podmiot2 .DaneKontaktowe }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Podmiot2 .DaneKontaktowe }
     */
    public Faktura_FA_2.Podmiot2 .DaneKontaktowe createFakturaPodmiot2DaneKontaktowe() {
        return new Faktura_FA_2.Podmiot2 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Podmiot1 .AdresKoresp }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Podmiot1 .AdresKoresp }
     */
    public Faktura_FA_2.Podmiot1 .AdresKoresp createFakturaPodmiot1AdresKoresp() {
        return new Faktura_FA_2.Podmiot1 .AdresKoresp();
    }

    /**
     * Create an instance of {@link Faktura_FA_2.Podmiot1 .DaneKontaktowe }
     * 
     * @return
     *     the new instance of {@link Faktura_FA_2.Podmiot1 .DaneKontaktowe }
     */
    public Faktura_FA_2.Podmiot1 .DaneKontaktowe createFakturaPodmiot1DaneKontaktowe() {
        return new Faktura_FA_2.Podmiot1 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link TNaglowek.KodFormularza }
     * 
     * @return
     *     the new instance of {@link TNaglowek.KodFormularza }
     */
    public TNaglowek.KodFormularza createTNaglowekKodFormularza() {
        return new TNaglowek.KodFormularza();
    }

}
