//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.wzor._2023._06._29._12648;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._01._05.ed.definicjetypy.TKodKraju;


/**
 * Informacje opisujące adres
 * 
 * <p>Java class for TAdres complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TAdres">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="KodKraju" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TKodKraju"/>
 *         <element name="AdresL1" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy512"/>
 *         <element name="AdresL2" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy512" minOccurs="0"/>
 *         <element name="GLN" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TGLN" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAdres", propOrder = {
    "kodKraju",
    "adresL1",
    "adresL2",
    "gln"
})
@XmlSeeAlso({
    Faktura_FA_2.Podmiot1.AdresKoresp.class
})
public class TAdres {

    /**
     * Kod Kraju [Country Code]
     * 
     */
    @XmlElement(name = "KodKraju", required = true)
    @XmlSchemaType(name = "normalizedString")
    protected TKodKraju kodKraju;
    /**
     * Adres [Address]
     * 
     */
    @XmlElement(name = "AdresL1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String adresL1;
    /**
     * Adres [Address]
     * 
     */
    @XmlElement(name = "AdresL2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String adresL2;
    /**
     * Globalny Numer Lokalizacyjny [Global Location Number]
     * 
     */
    @XmlElement(name = "GLN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String gln;

    /**
     * Kod Kraju [Country Code]
     * 
     * @return
     *     possible object is
     *     {@link TKodKraju }
     *     
     */
    public TKodKraju getKodKraju() {
        return kodKraju;
    }

    /**
     * Sets the value of the kodKraju property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodKraju }
     *     
     * @see #getKodKraju()
     */
    public void setKodKraju(TKodKraju value) {
        this.kodKraju = value;
    }

    /**
     * Adres [Address]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresL1() {
        return adresL1;
    }

    /**
     * Sets the value of the adresL1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAdresL1()
     */
    public void setAdresL1(String value) {
        this.adresL1 = value;
    }

    /**
     * Adres [Address]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresL2() {
        return adresL2;
    }

    /**
     * Sets the value of the adresL2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAdresL2()
     */
    public void setAdresL2(String value) {
        this.adresL2 = value;
    }

    /**
     * Globalny Numer Lokalizacyjny [Global Location Number]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGLN() {
        return gln;
    }

    /**
     * Sets the value of the gln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getGLN()
     */
    public void setGLN(String value) {
        this.gln = value;
    }

}
