//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.30 at 10:37:45 PM CET 
//


package pl.gov.crd.wzor._2023._06._29._12648;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Typ złożony, klucz-wartość
 * 
 * &lt;p&gt;Java class for TKluczWartosc complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="TKluczWartosc"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="NrWiersza" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TNaturalny" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="Klucz" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy"/&amp;gt;
 *         &amp;lt;element name="Wartosc" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TKluczWartosc", propOrder = {
    "nrWiersza",
    "klucz",
    "wartosc"
})
public class TKluczWartosc {

    @XmlElement(name = "NrWiersza")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger nrWiersza;
    @XmlElement(name = "Klucz", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String klucz;
    @XmlElement(name = "Wartosc", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String wartosc;

    /**
     * Gets the value of the nrWiersza property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNrWiersza() {
        return nrWiersza;
    }

    /**
     * Sets the value of the nrWiersza property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNrWiersza(BigInteger value) {
        this.nrWiersza = value;
    }

    /**
     * Gets the value of the klucz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlucz() {
        return klucz;
    }

    /**
     * Sets the value of the klucz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlucz(String value) {
        this.klucz = value;
    }

    /**
     * Gets the value of the wartosc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWartosc() {
        return wartosc;
    }

    /**
     * Sets the value of the wartosc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWartosc(String value) {
        this.wartosc = value;
    }

}
