//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.30 at 10:37:45 PM CET 
//


package pl.gov.crd.wzor._2023._06._29._12648;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for TOznaczenieProcedury.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="TOznaczenieProcedury"&amp;gt;
 *   &amp;lt;restriction base="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy"&amp;gt;
 *     &amp;lt;enumeration value="WSTO_EE"/&amp;gt;
 *     &amp;lt;enumeration value="IED"/&amp;gt;
 *     &amp;lt;enumeration value="TT_D"/&amp;gt;
 *     &amp;lt;enumeration value="I_42"/&amp;gt;
 *     &amp;lt;enumeration value="I_63"/&amp;gt;
 *     &amp;lt;enumeration value="B_SPV"/&amp;gt;
 *     &amp;lt;enumeration value="B_SPV_DOSTAWA"/&amp;gt;
 *     &amp;lt;enumeration value="B_MPV_PROWIZJA"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "TOznaczenieProcedury")
@XmlEnum
public enum TOznaczenieProcedury {


    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 2a rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    WSTO_EE,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 2b rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    IED,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 5 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    TT_D,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 8 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    I_42,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 9 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    I_63,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 10 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_SPV,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 11 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_SPV_DOSTAWA,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 12 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_MPV_PROWIZJA;

    public String value() {
        return name();
    }

    public static TOznaczenieProcedury fromValue(String v) {
        return valueOf(v);
    }

}
