//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.wzor._2023._06._29._12648;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Rodzaj faktury
 * 
 * <p>Java class for TRodzajFaktury</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="TRodzajFaktury">
 *   <restriction base="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy">
 *     <enumeration value="VAT"/>
 *     <enumeration value="KOR"/>
 *     <enumeration value="ZAL"/>
 *     <enumeration value="ROZ"/>
 *     <enumeration value="UPR"/>
 *     <enumeration value="KOR_ZAL"/>
 *     <enumeration value="KOR_ROZ"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "TRodzajFaktury")
@XmlEnum
public enum TRodzajFaktury {


    /**
     * Faktura podstawowa
     * 
     */
    VAT,

    /**
     * Faktura korygująca
     * 
     */
    KOR,

    /**
     * Faktura dokumentująca otrzymanie zapłaty lub jej części przed dokonaniem czynności oraz faktura wystawiona w związku z art. 106f ust. 4 ustawy
     * 
     */
    ZAL,

    /**
     * Faktura wystawiona w związku z art. 106f ust. 3 ustawy
     * 
     */
    ROZ,

    /**
     * Faktura, o której mowa w art. 106e ust. 5 pkt 3 ustawy
     * 
     */
    UPR,

    /**
     * Faktura korygująca fakturę dokumentującą otrzymanie zapłaty lub jej części przed dokonaniem czynności oraz fakturę wystawioną w związku z art. 106f ust. 4 ustawy
     * 
     */
    KOR_ZAL,

    /**
     * Faktura korygująca fakturę wystawioną w związku z art. 106f ust. 3 ustawy
     * 
     */
    KOR_ROZ;

    public String value() {
        return name();
    }

    public static TRodzajFaktury fromValue(String v) {
        return valueOf(v);
    }

}
