//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.ssea;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.ssea package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.ssea
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalacznikSSEA }
     * 
     * @return
     *     the new instance of {@link ZalacznikSSEA }
     */
    public ZalacznikSSEA createZalacznikSSEA() {
        return new ZalacznikSSEA();
    }

    /**
     * Create an instance of {@link TNaglowekSSEA }
     * 
     * @return
     *     the new instance of {@link TNaglowekSSEA }
     */
    public TNaglowekSSEA createTNaglowekSSEA() {
        return new TNaglowekSSEA();
    }

    /**
     * Create an instance of {@link ZalacznikSSEA.PozycjeSzczegolowe }
     * 
     * @return
     *     the new instance of {@link ZalacznikSSEA.PozycjeSzczegolowe }
     */
    public ZalacznikSSEA.PozycjeSzczegolowe createZalacznikSSEAPozycjeSzczegolowe() {
        return new ZalacznikSSEA.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekSSEA.KodFormularza }
     * 
     * @return
     *     the new instance of {@link TNaglowekSSEA.KodFormularza }
     */
    public TNaglowekSSEA.KodFormularza createTNaglowekSSEAKodFormularza() {
        return new TNaglowekSSEA.KodFormularza();
    }

}
