//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citpd;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import pl.gov.crd.xml.schematy.dziedzinowe.mf._2023._09._06.ed.kodykrajow.TKodKraju;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Naglowek" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TNaglowek_CIT_PD"/>
 *         <element name="PozycjeSzczegolowe">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <sequence>
 *                     <element name="P_8" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_9" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_10" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_11" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_12" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_13" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
 *                   </sequence>
 *                   <sequence>
 *                     <element name="P_14" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                     <element name="P_15" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_16" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                     <element name="P_17" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_18" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
 *                   </sequence>
 *                   <element name="P_D" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <sequence>
 *                               <element name="P_D19" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TRodzajPodmiotu"/>
 *                               <element name="P_D20" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrNIP"/>
 *                               <sequence minOccurs="0">
 *                                 <element name="P_D21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrDokumentuStwierdzajacegoTozsamosc"/>
 *                                 <element name="P_D22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TRodzajIdentyfikacji"/>
 *                                 <element name="P_D23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TKodKrajuWydania"/>
 *                               </sequence>
 *                               <element name="P_D24">
 *                                 <simpleType>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                     <minLength value="1"/>
 *                                     <maxLength value="240"/>
 *                                   </restriction>
 *                                 </simpleType>
 *                               </element>
 *                             </sequence>
 *                             <sequence>
 *                               <element name="P_D25A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
 *                               <element name="P_D26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                               <element name="P_D27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                               <element name="P_D28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
 *                               <element name="P_D29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
 *                               <element name="P_D30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
 *                               <element name="P_D31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
 *                               <element name="P_D32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
 *                               <element name="P_D33" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
 *                             </sequence>
 *                           </sequence>
 *                           <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naglowek",
    "pozycjeSzczegolowe"
})
@XmlRootElement(name = "Zalacznik_CIT_PD")
public class ZalacznikCITPD {

    @XmlElement(name = "Naglowek", required = true)
    protected TNaglowekCITPD naglowek;
    /**
     * Podstawa opodatkowania, obliczenie podatku, dane dodatkowe - informacje o podmiotach powiązanych
     * 
     */
    @XmlElement(name = "PozycjeSzczegolowe", required = true)
    protected PozycjeSzczegolowe pozycjeSzczegolowe;

    /**
     * Gets the value of the naglowek property.
     * 
     * @return
     *     possible object is
     *     {@link TNaglowekCITPD }
     *     
     */
    public TNaglowekCITPD getNaglowek() {
        return naglowek;
    }

    /**
     * Sets the value of the naglowek property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNaglowekCITPD }
     *     
     */
    public void setNaglowek(TNaglowekCITPD value) {
        this.naglowek = value;
    }

    /**
     * Podstawa opodatkowania, obliczenie podatku, dane dodatkowe - informacje o podmiotach powiązanych
     * 
     * @return
     *     possible object is
     *     {@link PozycjeSzczegolowe }
     *     
     */
    public PozycjeSzczegolowe getPozycjeSzczegolowe() {
        return pozycjeSzczegolowe;
    }

    /**
     * Sets the value of the pozycjeSzczegolowe property.
     * 
     * @param value
     *     allowed object is
     *     {@link PozycjeSzczegolowe }
     *     
     * @see #getPozycjeSzczegolowe()
     */
    public void setPozycjeSzczegolowe( PozycjeSzczegolowe value) {
        this.pozycjeSzczegolowe = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <sequence>
     *           <element name="P_8" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_9" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_10" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_11" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_12" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_13" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
     *         </sequence>
     *         <sequence>
     *           <element name="P_14" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *           <element name="P_15" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_16" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *           <element name="P_17" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_18" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
     *         </sequence>
     *         <element name="P_D" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <sequence>
     *                     <element name="P_D19" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TRodzajPodmiotu"/>
     *                     <element name="P_D20" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrNIP"/>
     *                     <sequence minOccurs="0">
     *                       <element name="P_D21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrDokumentuStwierdzajacegoTozsamosc"/>
     *                       <element name="P_D22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TRodzajIdentyfikacji"/>
     *                       <element name="P_D23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TKodKrajuWydania"/>
     *                     </sequence>
     *                     <element name="P_D24">
     *                       <simpleType>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                           <minLength value="1"/>
     *                           <maxLength value="240"/>
     *                         </restriction>
     *                       </simpleType>
     *                     </element>
     *                   </sequence>
     *                   <sequence>
     *                     <element name="P_D25A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
     *                     <element name="P_D26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                     <element name="P_D27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                     <element name="P_D28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
     *                     <element name="P_D29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
     *                     <element name="P_D30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
     *                     <element name="P_D31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
     *                     <element name="P_D32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
     *                     <element name="P_D33" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
     *                   </sequence>
     *                 </sequence>
     *                 <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p8",
        "p9",
        "p10",
        "p11",
        "p12",
        "p13",
        "p14",
        "p15",
        "p16",
        "p17",
        "p18",
        "pd"
    })
    public static class PozycjeSzczegolowe {

        /**
         * Usługi doradcze, badania rynku, usługi reklamowe, zarządzania i kontroli, przetwarzania danych, ubezpieczeń, gwarancji i poręczeń oraz usługi o podobnym charakterze
         * 
         */
        @XmlElement(name = "P_8")
        protected BigDecimal p8;
        /**
         * Wszelkiego rodzaju opłaty i należności za korzystanie lub prawo do korzystania z praw lub wartości, o których mowa w art. 16b ust. 1 pkt 4-7 ustawy
         * 
         */
        @XmlElement(name = "P_9")
        protected BigDecimal p9;
        /**
         * Przeniesienia ryzyka niewypłacalności dłużnika z tytułu pożyczek, innych niż udzielonych przez banki i spółdzielcze kasy oszczędnościowo-kredytowe, w tym w ramach zobowiązań wynikających z pochodnych instrumentów finansowych oraz świadczeń o podobnym charakterze
         * 
         */
        @XmlElement(name = "P_10")
        protected BigDecimal p10;
        /**
         * Koszty finansowania dłużnego związane z uzyskaniem środków finansowych i korzystaniem z tych środków, w szczególności odsetki, opłaty, prowizje, premie, część odsetkowa raty leasingowej, kary i opłaty za opóźnienie w zapłacie zobowiązań oraz koszty zabezpieczenia zobowiązań, w tym koszty pochodnych instrumentów finansowych
         * 
         */
        @XmlElement(name = "P_11")
        protected BigDecimal p11;
        /**
         * Opłaty i wynagrodzenia za przeniesienie funkcji, aktywów lub ryzyk
         * 
         */
        @XmlElement(name = "P_12")
        protected BigDecimal p12;
        /**
         * Podstawa opodatkowania (po zaokrągleniu do pełnych złotych)
         * 
         */
        @XmlElement(name = "P_13", required = true)
        protected BigInteger p13;
        /**
         * Podatek według stawki 19% - art. 24aa ust. 1 ustawy, obliczony od podstawy z poz. 13
         * 
         */
        @XmlElement(name = "P_14", required = true)
        protected BigDecimal p14;
        /**
         * Odliczenie zryczałtowanego podatku dochodowego, o którym mowa w art. 21 ustawy, pobranego od wypłat z tytułu kosztów uwzględnionych w podstawie opodatkowania, zgodnie z art. 24aa ust. 8 ustawy
         * 
         */
        @XmlElement(name = "P_15")
        protected BigInteger p15;
        /**
         * Podatek po odliczeniu
         * 
         */
        @XmlElement(name = "P_16", required = true)
        protected BigDecimal p16;
        /**
         * Doliczenie zmniejszenia pobranego zryczałtowanego podatku dochodowego zgodnie z art. 24aa ust. 8 ustawy
         * 
         */
        @XmlElement(name = "P_17")
        protected BigInteger p17;
        /**
         * Podatek do zapłaty (po zaokrągleniu do pełnych złotych)
         * 
         */
        @XmlElement(name = "P_18", required = true)
        protected BigInteger p18;
        /**
         * Dane dodatkowe - informacje o podmiotach powiązanych
         * 
         */
        @XmlElement(name = "P_D", required = true)
        protected List<PD> pd;

        /**
         * Usługi doradcze, badania rynku, usługi reklamowe, zarządzania i kontroli, przetwarzania danych, ubezpieczeń, gwarancji i poręczeń oraz usługi o podobnym charakterze
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP8() {
            return p8;
        }

        /**
         * Sets the value of the p8 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP8()
         */
        public void setP8(BigDecimal value) {
            this.p8 = value;
        }

        /**
         * Wszelkiego rodzaju opłaty i należności za korzystanie lub prawo do korzystania z praw lub wartości, o których mowa w art. 16b ust. 1 pkt 4-7 ustawy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP9() {
            return p9;
        }

        /**
         * Sets the value of the p9 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP9()
         */
        public void setP9(BigDecimal value) {
            this.p9 = value;
        }

        /**
         * Przeniesienia ryzyka niewypłacalności dłużnika z tytułu pożyczek, innych niż udzielonych przez banki i spółdzielcze kasy oszczędnościowo-kredytowe, w tym w ramach zobowiązań wynikających z pochodnych instrumentów finansowych oraz świadczeń o podobnym charakterze
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP10() {
            return p10;
        }

        /**
         * Sets the value of the p10 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP10()
         */
        public void setP10(BigDecimal value) {
            this.p10 = value;
        }

        /**
         * Koszty finansowania dłużnego związane z uzyskaniem środków finansowych i korzystaniem z tych środków, w szczególności odsetki, opłaty, prowizje, premie, część odsetkowa raty leasingowej, kary i opłaty za opóźnienie w zapłacie zobowiązań oraz koszty zabezpieczenia zobowiązań, w tym koszty pochodnych instrumentów finansowych
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP11() {
            return p11;
        }

        /**
         * Sets the value of the p11 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP11()
         */
        public void setP11(BigDecimal value) {
            this.p11 = value;
        }

        /**
         * Opłaty i wynagrodzenia za przeniesienie funkcji, aktywów lub ryzyk
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP12() {
            return p12;
        }

        /**
         * Sets the value of the p12 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP12()
         */
        public void setP12(BigDecimal value) {
            this.p12 = value;
        }

        /**
         * Podstawa opodatkowania (po zaokrągleniu do pełnych złotych)
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP13() {
            return p13;
        }

        /**
         * Sets the value of the p13 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP13()
         */
        public void setP13(BigInteger value) {
            this.p13 = value;
        }

        /**
         * Podatek według stawki 19% - art. 24aa ust. 1 ustawy, obliczony od podstawy z poz. 13
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP14() {
            return p14;
        }

        /**
         * Sets the value of the p14 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP14()
         */
        public void setP14(BigDecimal value) {
            this.p14 = value;
        }

        /**
         * Odliczenie zryczałtowanego podatku dochodowego, o którym mowa w art. 21 ustawy, pobranego od wypłat z tytułu kosztów uwzględnionych w podstawie opodatkowania, zgodnie z art. 24aa ust. 8 ustawy
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP15() {
            return p15;
        }

        /**
         * Sets the value of the p15 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP15()
         */
        public void setP15(BigInteger value) {
            this.p15 = value;
        }

        /**
         * Podatek po odliczeniu
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP16() {
            return p16;
        }

        /**
         * Sets the value of the p16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP16()
         */
        public void setP16(BigDecimal value) {
            this.p16 = value;
        }

        /**
         * Doliczenie zmniejszenia pobranego zryczałtowanego podatku dochodowego zgodnie z art. 24aa ust. 8 ustawy
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP17() {
            return p17;
        }

        /**
         * Sets the value of the p17 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP17()
         */
        public void setP17(BigInteger value) {
            this.p17 = value;
        }

        /**
         * Podatek do zapłaty (po zaokrągleniu do pełnych złotych)
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP18() {
            return p18;
        }

        /**
         * Sets the value of the p18 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP18()
         */
        public void setP18(BigInteger value) {
            this.p18 = value;
        }

        /**
         * Dane dodatkowe - informacje o podmiotach powiązanych
         * 
         * Gets the value of the pd property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pd property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getPD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PD }
         * </p>
         * 
         * 
         * @return
         *     The value of the pd property.
         */
        public List<PD> getPD() {
            if (pd == null) {
                pd = new ArrayList<>();
            }
            return this.pd;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <sequence>
         *           <element name="P_D19" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TRodzajPodmiotu"/>
         *           <element name="P_D20" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrNIP"/>
         *           <sequence minOccurs="0">
         *             <element name="P_D21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrDokumentuStwierdzajacegoTozsamosc"/>
         *             <element name="P_D22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TRodzajIdentyfikacji"/>
         *             <element name="P_D23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITPD/}TKodKrajuWydania"/>
         *           </sequence>
         *           <element name="P_D24">
         *             <simpleType>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *                 <minLength value="1"/>
         *                 <maxLength value="240"/>
         *               </restriction>
         *             </simpleType>
         *           </element>
         *         </sequence>
         *         <sequence>
         *           <element name="P_D25A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/}TKodKraju"/>
         *           <element name="P_D26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_D27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_D28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TJednAdmin" minOccurs="0"/>
         *           <element name="P_D29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
         *           <element name="P_D30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
         *           <element name="P_D31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
         *           <element name="P_D32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TMiejscowosc"/>
         *           <element name="P_D33" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
         *         </sequence>
         *       </sequence>
         *       <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pd19",
            "pd20",
            "pd21",
            "pd22",
            "pd23",
            "pd24",
            "pd25A",
            "pd26",
            "pd27",
            "pd28",
            "pd29",
            "pd30",
            "pd31",
            "pd32",
            "pd33"
        })
        public static class PD {

            /**
             * Podmiot powiązany jest: 1 - podmiotem, który spełnia warunki, o których mowa w art. 24aa ust. 2 pkt 1-3 ustawy, 2 - spółką niebędącą osobą prawną mającą siedzibę lub zarząd na terytorium Rzeczypospolitej Polskiej, o której mowa w art. 24aa ust. 14 pkt 1 ustawy, 3 - podmiotem niemającym siedziby lub zarządu na terytorium Rzeczypospolitej Polskiej, o którym mowa w art. 24aa ust. 14 pkt 2 ustawy, 4 - podmiotem, który spełnia warunki, o których mowa w art. 24aa ust. 15 ustawy
             * 
             */
            @XmlElement(name = "P_D19")
            protected byte pd19;
            /**
             * Identyfikator podatkowy NIP
             * 
             */
            @XmlElement(name = "P_D20", required = true)
            protected String pd20;
            /**
             * Zagraniczny numer identyfikacyjny
             * 
             */
            @XmlElement(name = "P_D21")
            protected String pd21;
            /**
             * Rodzaj zagranicznego numeru identyfikacyjnego
             * 
             */
            @XmlElement(name = "P_D22")
            protected Byte pd22;
            /**
             * Kod kraju wydania zagranicznego numeru identyfikacyjnego
             * 
             */
            @XmlElement(name = "P_D23")
            @XmlSchemaType(name = "normalizedString")
            protected TKodKraju pd23;
            /**
             * Nazwa pełna podmiotu
             * 
             */
            @XmlElement(name = "P_D24", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String pd24;
            /**
             * Kraj
             * 
             */
            @XmlElement(name = "P_D25A", required = true)
            @XmlSchemaType(name = "normalizedString")
            protected TKodKraju pd25A;
            /**
             * Województwo
             * 
             */
            @XmlElement(name = "P_D26")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pd26;
            /**
             * Powiat
             * 
             */
            @XmlElement(name = "P_D27")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pd27;
            /**
             * Gmina
             * 
             */
            @XmlElement(name = "P_D28")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pd28;
            /**
             * Nazwa ulicy
             * 
             */
            @XmlElement(name = "P_D29")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pd29;
            /**
             * Numer budynku
             * 
             */
            @XmlElement(name = "P_D30")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pd30;
            /**
             * Numer lokalu
             * 
             */
            @XmlElement(name = "P_D31")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pd31;
            /**
             * Nazwa miejscowości
             * 
             */
            @XmlElement(name = "P_D32", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pd32;
            /**
             * Kod pocztowy
             * 
             */
            @XmlElement(name = "P_D33")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pd33;
            @XmlAttribute(name = "typ", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String typ;

            /**
             * Podmiot powiązany jest: 1 - podmiotem, który spełnia warunki, o których mowa w art. 24aa ust. 2 pkt 1-3 ustawy, 2 - spółką niebędącą osobą prawną mającą siedzibę lub zarząd na terytorium Rzeczypospolitej Polskiej, o której mowa w art. 24aa ust. 14 pkt 1 ustawy, 3 - podmiotem niemającym siedziby lub zarządu na terytorium Rzeczypospolitej Polskiej, o którym mowa w art. 24aa ust. 14 pkt 2 ustawy, 4 - podmiotem, który spełnia warunki, o których mowa w art. 24aa ust. 15 ustawy
             * 
             */
            public byte getPD19() {
                return pd19;
            }

            /**
             * Sets the value of the pd19 property.
             * 
             */
            public void setPD19(byte value) {
                this.pd19 = value;
            }

            /**
             * Identyfikator podatkowy NIP
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD20() {
                return pd20;
            }

            /**
             * Sets the value of the pd20 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD20()
             */
            public void setPD20(String value) {
                this.pd20 = value;
            }

            /**
             * Zagraniczny numer identyfikacyjny
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD21() {
                return pd21;
            }

            /**
             * Sets the value of the pd21 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD21()
             */
            public void setPD21(String value) {
                this.pd21 = value;
            }

            /**
             * Rodzaj zagranicznego numeru identyfikacyjnego
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getPD22() {
                return pd22;
            }

            /**
             * Sets the value of the pd22 property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             * @see #getPD22()
             */
            public void setPD22(Byte value) {
                this.pd22 = value;
            }

            /**
             * Kod kraju wydania zagranicznego numeru identyfikacyjnego
             * 
             * @return
             *     possible object is
             *     {@link TKodKraju }
             *     
             */
            public TKodKraju getPD23() {
                return pd23;
            }

            /**
             * Sets the value of the pd23 property.
             * 
             * @param value
             *     allowed object is
             *     {@link TKodKraju }
             *     
             * @see #getPD23()
             */
            public void setPD23(TKodKraju value) {
                this.pd23 = value;
            }

            /**
             * Nazwa pełna podmiotu
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD24() {
                return pd24;
            }

            /**
             * Sets the value of the pd24 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD24()
             */
            public void setPD24(String value) {
                this.pd24 = value;
            }

            /**
             * Kraj
             * 
             * @return
             *     possible object is
             *     {@link TKodKraju }
             *     
             */
            public TKodKraju getPD25A() {
                return pd25A;
            }

            /**
             * Sets the value of the pd25A property.
             * 
             * @param value
             *     allowed object is
             *     {@link TKodKraju }
             *     
             * @see #getPD25A()
             */
            public void setPD25A(TKodKraju value) {
                this.pd25A = value;
            }

            /**
             * Województwo
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD26() {
                return pd26;
            }

            /**
             * Sets the value of the pd26 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD26()
             */
            public void setPD26(String value) {
                this.pd26 = value;
            }

            /**
             * Powiat
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD27() {
                return pd27;
            }

            /**
             * Sets the value of the pd27 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD27()
             */
            public void setPD27(String value) {
                this.pd27 = value;
            }

            /**
             * Gmina
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD28() {
                return pd28;
            }

            /**
             * Sets the value of the pd28 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD28()
             */
            public void setPD28(String value) {
                this.pd28 = value;
            }

            /**
             * Nazwa ulicy
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD29() {
                return pd29;
            }

            /**
             * Sets the value of the pd29 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD29()
             */
            public void setPD29(String value) {
                this.pd29 = value;
            }

            /**
             * Numer budynku
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD30() {
                return pd30;
            }

            /**
             * Sets the value of the pd30 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD30()
             */
            public void setPD30(String value) {
                this.pd30 = value;
            }

            /**
             * Numer lokalu
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD31() {
                return pd31;
            }

            /**
             * Sets the value of the pd31 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD31()
             */
            public void setPD31(String value) {
                this.pd31 = value;
            }

            /**
             * Nazwa miejscowości
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD32() {
                return pd32;
            }

            /**
             * Sets the value of the pd32 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD32()
             */
            public void setPD32(String value) {
                this.pd32 = value;
            }

            /**
             * Kod pocztowy
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPD33() {
                return pd33;
            }

            /**
             * Sets the value of the pd33 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPD33()
             */
            public void setPD33(String value) {
                this.pd33 = value;
            }

            /**
             * Gets the value of the typ property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTyp() {
                if (typ == null) {
                    return "G";
                } else {
                    return typ;
                }
            }

            /**
             * Sets the value of the typ property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTyp(String value) {
                this.typ = value;
            }

        }

    }

}
