//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citmit;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citmit package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citmit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalacznikCITMIT }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITMIT }
     */
    public ZalacznikCITMIT createZalacznikCITMIT() {
        return new ZalacznikCITMIT();
    }

    /**
     * Create an instance of {@link ZalacznikCITMIT.PozycjeSzczegolowe }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITMIT.PozycjeSzczegolowe }
     */
    public ZalacznikCITMIT.PozycjeSzczegolowe createZalacznikCITMITPozycjeSzczegolowe() {
        return new ZalacznikCITMIT.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekCITMIT }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITMIT }
     */
    public TNaglowekCITMIT createTNaglowekCITMIT() {
        return new TNaglowekCITMIT();
    }

    /**
     * Create an instance of {@link ZalacznikCITMIT.PozycjeSzczegolowe.PB }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITMIT.PozycjeSzczegolowe.PB }
     */
    public ZalacznikCITMIT.PozycjeSzczegolowe.PB createZalacznikCITMITPozycjeSzczegolowePB() {
        return new ZalacznikCITMIT.PozycjeSzczegolowe.PB();
    }

    /**
     * Create an instance of {@link TNaglowekCITMIT.KodFormularza }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITMIT.KodFormularza }
     */
    public TNaglowekCITMIT.KodFormularza createTNaglowekCITMITKodFormularza() {
        return new TNaglowekCITMIT.KodFormularza();
    }

    /**
     * Create an instance of {@link TNaglowekCITMIT.OkresOd }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITMIT.OkresOd }
     */
    public TNaglowekCITMIT.OkresOd createTNaglowekCITMITOkresOd() {
        return new TNaglowekCITMIT.OkresOd();
    }

    /**
     * Create an instance of {@link TNaglowekCITMIT.OkresDo }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITMIT.OkresDo }
     */
    public TNaglowekCITMIT.OkresDo createTNaglowekCITMITOkresDo() {
        return new TNaglowekCITMIT.OkresDo();
    }

}
