//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.citmit;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Naglowek" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/CITMIT/}TNaglowek_CIT_MIT"/>
 *         <element name="PozycjeSzczegolowe">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="P_B" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="P_B8" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
 *                             <element name="P_B9">
 *                               <simpleType>
 *                                 <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna">
 *                                   <minExclusive value="0"/>
 *                                 </restriction>
 *                               </simpleType>
 *                             </element>
 *                           </sequence>
 *                           <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <sequence>
 *                     <element name="P_10" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_11" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_12" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_13" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_14" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_15" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_16" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_17" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_18" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_19" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_20" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_24" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_25" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                     <element name="P_32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
 *                   </sequence>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naglowek",
    "pozycjeSzczegolowe"
})
@XmlRootElement(name = "Zalacznik_CIT_MIT")
public class ZalacznikCITMIT {

    @XmlElement(name = "Naglowek", required = true)
    protected TNaglowekCITMIT naglowek;
    /**
     * Dane dotyczące środków trwałych, podstawa opodatkowania
     * 
     */
    @XmlElement(name = "PozycjeSzczegolowe", required = true)
    protected PozycjeSzczegolowe pozycjeSzczegolowe;

    /**
     * Gets the value of the naglowek property.
     * 
     * @return
     *     possible object is
     *     {@link TNaglowekCITMIT }
     *     
     */
    public TNaglowekCITMIT getNaglowek() {
        return naglowek;
    }

    /**
     * Sets the value of the naglowek property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNaglowekCITMIT }
     *     
     */
    public void setNaglowek(TNaglowekCITMIT value) {
        this.naglowek = value;
    }

    /**
     * Dane dotyczące środków trwałych, podstawa opodatkowania
     * 
     * @return
     *     possible object is
     *     {@link PozycjeSzczegolowe }
     *     
     */
    public PozycjeSzczegolowe getPozycjeSzczegolowe() {
        return pozycjeSzczegolowe;
    }

    /**
     * Sets the value of the pozycjeSzczegolowe property.
     * 
     * @param value
     *     allowed object is
     *     {@link PozycjeSzczegolowe }
     *     
     * @see #getPozycjeSzczegolowe()
     */
    public void setPozycjeSzczegolowe( PozycjeSzczegolowe value) {
        this.pozycjeSzczegolowe = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="P_B" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="P_B8" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
     *                   <element name="P_B9">
     *                     <simpleType>
     *                       <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna">
     *                         <minExclusive value="0"/>
     *                       </restriction>
     *                     </simpleType>
     *                   </element>
     *                 </sequence>
     *                 <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <sequence>
     *           <element name="P_10" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_11" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_12" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_13" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_14" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_15" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_16" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_17" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_18" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_19" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_20" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_24" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_25" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *           <element name="P_32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna" minOccurs="0"/>
     *         </sequence>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pb",
        "p10",
        "p11",
        "p12",
        "p13",
        "p14",
        "p15",
        "p16",
        "p17",
        "p18",
        "p19",
        "p20",
        "p21",
        "p22",
        "p23",
        "p24",
        "p25",
        "p26",
        "p27",
        "p28",
        "p29",
        "p30",
        "p31",
        "p32"
    })
    public static class PozycjeSzczegolowe {

        /**
         * Określenie środka trwałego / środków trwałych
         * 
         */
        @XmlElement(name = "P_B", required = true)
        protected List<PB> pb;
        /**
         * Podstawa opodatkowania 1
         * 
         */
        @XmlElement(name = "P_10")
        protected BigInteger p10;
        /**
         * Podstawa opodatkowania 2
         * 
         */
        @XmlElement(name = "P_11")
        protected BigInteger p11;
        /**
         * Podstawa opodatkowania 3
         * 
         */
        @XmlElement(name = "P_12")
        protected BigInteger p12;
        /**
         * Podstawa opodatkowania 4
         * 
         */
        @XmlElement(name = "P_13")
        protected BigInteger p13;
        /**
         * Podstawa opodatkowania 5
         * 
         */
        @XmlElement(name = "P_14")
        protected BigInteger p14;
        /**
         * Podstawa opodatkowania 6
         * 
         */
        @XmlElement(name = "P_15")
        protected BigInteger p15;
        /**
         * Podstawa opodatkowania 7
         * 
         */
        @XmlElement(name = "P_16")
        protected BigInteger p16;
        /**
         * Podstawa opodatkowania 8
         * 
         */
        @XmlElement(name = "P_17")
        protected BigInteger p17;
        /**
         * Podstawa opodatkowania 9
         * 
         */
        @XmlElement(name = "P_18")
        protected BigInteger p18;
        /**
         * Podstawa opodatkowania 10
         * 
         */
        @XmlElement(name = "P_19")
        protected BigInteger p19;
        /**
         * Podstawa opodatkowania 11
         * 
         */
        @XmlElement(name = "P_20")
        protected BigInteger p20;
        /**
         * Podstawa opodatkowania 12
         * 
         */
        @XmlElement(name = "P_21")
        protected BigInteger p21;
        /**
         * Podstawa opodatkowania 13
         * 
         */
        @XmlElement(name = "P_22")
        protected BigInteger p22;
        /**
         * Podstawa opodatkowania 14
         * 
         */
        @XmlElement(name = "P_23")
        protected BigInteger p23;
        /**
         * Podstawa opodatkowania 15
         * 
         */
        @XmlElement(name = "P_24")
        protected BigInteger p24;
        /**
         * Podstawa opodatkowania 16
         * 
         */
        @XmlElement(name = "P_25")
        protected BigInteger p25;
        /**
         * Podstawa opodatkowania 17
         * 
         */
        @XmlElement(name = "P_26")
        protected BigInteger p26;
        /**
         * Podstawa opodatkowania 18
         * 
         */
        @XmlElement(name = "P_27")
        protected BigInteger p27;
        /**
         * Podstawa opodatkowania 19
         * 
         */
        @XmlElement(name = "P_28")
        protected BigInteger p28;
        /**
         * Podstawa opodatkowania 20
         * 
         */
        @XmlElement(name = "P_29")
        protected BigInteger p29;
        /**
         * Podstawa opodatkowania 21
         * 
         */
        @XmlElement(name = "P_30")
        protected BigInteger p30;
        /**
         * Podstawa opodatkowania 22
         * 
         */
        @XmlElement(name = "P_31")
        protected BigInteger p31;
        /**
         * Podstawa opodatkowania 23
         * 
         */
        @XmlElement(name = "P_32")
        protected BigInteger p32;

        /**
         * Określenie środka trwałego / środków trwałych
         * 
         * Gets the value of the pb property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pb property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getPB().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PB }
         * </p>
         * 
         * 
         * @return
         *     The value of the pb property.
         */
        public List<PB> getPB() {
            if (pb == null) {
                pb = new ArrayList<>();
            }
            return this.pb;
        }

        /**
         * Podstawa opodatkowania 1
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP10() {
            return p10;
        }

        /**
         * Sets the value of the p10 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP10()
         */
        public void setP10(BigInteger value) {
            this.p10 = value;
        }

        /**
         * Podstawa opodatkowania 2
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP11() {
            return p11;
        }

        /**
         * Sets the value of the p11 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP11()
         */
        public void setP11(BigInteger value) {
            this.p11 = value;
        }

        /**
         * Podstawa opodatkowania 3
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP12() {
            return p12;
        }

        /**
         * Sets the value of the p12 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP12()
         */
        public void setP12(BigInteger value) {
            this.p12 = value;
        }

        /**
         * Podstawa opodatkowania 4
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP13() {
            return p13;
        }

        /**
         * Sets the value of the p13 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP13()
         */
        public void setP13(BigInteger value) {
            this.p13 = value;
        }

        /**
         * Podstawa opodatkowania 5
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP14() {
            return p14;
        }

        /**
         * Sets the value of the p14 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP14()
         */
        public void setP14(BigInteger value) {
            this.p14 = value;
        }

        /**
         * Podstawa opodatkowania 6
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP15() {
            return p15;
        }

        /**
         * Sets the value of the p15 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP15()
         */
        public void setP15(BigInteger value) {
            this.p15 = value;
        }

        /**
         * Podstawa opodatkowania 7
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP16() {
            return p16;
        }

        /**
         * Sets the value of the p16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP16()
         */
        public void setP16(BigInteger value) {
            this.p16 = value;
        }

        /**
         * Podstawa opodatkowania 8
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP17() {
            return p17;
        }

        /**
         * Sets the value of the p17 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP17()
         */
        public void setP17(BigInteger value) {
            this.p17 = value;
        }

        /**
         * Podstawa opodatkowania 9
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP18() {
            return p18;
        }

        /**
         * Sets the value of the p18 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP18()
         */
        public void setP18(BigInteger value) {
            this.p18 = value;
        }

        /**
         * Podstawa opodatkowania 10
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP19() {
            return p19;
        }

        /**
         * Sets the value of the p19 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP19()
         */
        public void setP19(BigInteger value) {
            this.p19 = value;
        }

        /**
         * Podstawa opodatkowania 11
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP20() {
            return p20;
        }

        /**
         * Sets the value of the p20 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP20()
         */
        public void setP20(BigInteger value) {
            this.p20 = value;
        }

        /**
         * Podstawa opodatkowania 12
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP21() {
            return p21;
        }

        /**
         * Sets the value of the p21 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP21()
         */
        public void setP21(BigInteger value) {
            this.p21 = value;
        }

        /**
         * Podstawa opodatkowania 13
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP22() {
            return p22;
        }

        /**
         * Sets the value of the p22 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP22()
         */
        public void setP22(BigInteger value) {
            this.p22 = value;
        }

        /**
         * Podstawa opodatkowania 14
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP23() {
            return p23;
        }

        /**
         * Sets the value of the p23 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP23()
         */
        public void setP23(BigInteger value) {
            this.p23 = value;
        }

        /**
         * Podstawa opodatkowania 15
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP24() {
            return p24;
        }

        /**
         * Sets the value of the p24 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP24()
         */
        public void setP24(BigInteger value) {
            this.p24 = value;
        }

        /**
         * Podstawa opodatkowania 16
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP25() {
            return p25;
        }

        /**
         * Sets the value of the p25 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP25()
         */
        public void setP25(BigInteger value) {
            this.p25 = value;
        }

        /**
         * Podstawa opodatkowania 17
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP26() {
            return p26;
        }

        /**
         * Sets the value of the p26 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP26()
         */
        public void setP26(BigInteger value) {
            this.p26 = value;
        }

        /**
         * Podstawa opodatkowania 18
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP27() {
            return p27;
        }

        /**
         * Sets the value of the p27 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP27()
         */
        public void setP27(BigInteger value) {
            this.p27 = value;
        }

        /**
         * Podstawa opodatkowania 19
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP28() {
            return p28;
        }

        /**
         * Sets the value of the p28 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP28()
         */
        public void setP28(BigInteger value) {
            this.p28 = value;
        }

        /**
         * Podstawa opodatkowania 20
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP29() {
            return p29;
        }

        /**
         * Sets the value of the p29 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP29()
         */
        public void setP29(BigInteger value) {
            this.p29 = value;
        }

        /**
         * Podstawa opodatkowania 21
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP30() {
            return p30;
        }

        /**
         * Sets the value of the p30 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP30()
         */
        public void setP30(BigInteger value) {
            this.p30 = value;
        }

        /**
         * Podstawa opodatkowania 22
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP31() {
            return p31;
        }

        /**
         * Sets the value of the p31 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP31()
         */
        public void setP31(BigInteger value) {
            this.p31 = value;
        }

        /**
         * Podstawa opodatkowania 23
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP32() {
            return p32;
        }

        /**
         * Sets the value of the p32 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP32()
         */
        public void setP32(BigInteger value) {
            this.p32 = value;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="P_B8" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
         *         <element name="P_B9">
         *           <simpleType>
         *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna">
         *               <minExclusive value="0"/>
         *             </restriction>
         *           </simpleType>
         *         </element>
         *       </sequence>
         *       <attribute name="typ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="G" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pb8",
            "pb9"
        })
        public static class PB {

            /**
             * Nazwa środka trwałego / środków trwałych
             * 
             */
            @XmlElement(name = "P_B8", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String pb8;
            /**
             * Liczba
             * 
             */
            @XmlElement(name = "P_B9", required = true)
            protected BigDecimal pb9;
            @XmlAttribute(name = "typ", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String typ;

            /**
             * Nazwa środka trwałego / środków trwałych
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPB8() {
                return pb8;
            }

            /**
             * Sets the value of the pb8 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             * @see #getPB8()
             */
            public void setPB8(String value) {
                this.pb8 = value;
            }

            /**
             * Liczba
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPB9() {
                return pb9;
            }

            /**
             * Sets the value of the pb9 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             * @see #getPB9()
             */
            public void setPB9(BigDecimal value) {
                this.pb9 = value;
            }

            /**
             * Gets the value of the typ property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTyp() {
                if (typ == null) {
                    return "G";
                } else {
                    return typ;
                }
            }

            /**
             * Sets the value of the typ property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTyp(String value) {
                this.typ = value;
            }

        }

    }

}
