//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.sser;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.ssea.ZalacznikSSEA;
import pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._02._05.ed.ssera.ZalacznikSSERA;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Naglowek" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TNaglowek_SSE-R"/>
 *         <element name="Podmiot1">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TPodmiotDowolnyBezAdresu">
 *                 <attribute name="rola" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Składający" />
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="PozycjeSzczegolowe">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="P_7" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1_2"/>
 *                   <element name="P_8" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1_3"/>
 *                   <element name="P_9" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TKodStrefy"/>
 *                   <element name="P_10" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy" minOccurs="0"/>
 *                   <element name="P_11" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TData">
 *                         <minInclusive value="1995-10-01"/>
 *                         <maxInclusive value="2000-12-31"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="P_12" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TData" minOccurs="0"/>
 *                   <element name="P_13" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TData">
 *                         <minInclusive value="2004-05-01"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="P_14" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1_2"/>
 *                   <element name="P_15" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_16" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_17" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_18" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_19" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <sequence minOccurs="0">
 *                     <element name="P_20A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
 *                     <element name="P_20" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   </sequence>
 *                   <element name="P_23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_24" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_25" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <sequence>
 *                     <element name="P_26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                     <element name="P_30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   </sequence>
 *                   <element name="P_31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
 *                   <element name="P_32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
 *                   <element name="P_33" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_34" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_35" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_36" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_37" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_38" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_39" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_40" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_41" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_42" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_43" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_44" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <choice minOccurs="0">
 *                     <element name="P_45" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
 *                     <element name="P_46" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   </choice>
 *                   <element name="P_47" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_48" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_49" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_50" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_51" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_52" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_53" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_54" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_55" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_56" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
 *                   <element name="P_57" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_58" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_59" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
 *                   <element name="P_60" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_61" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <element name="P_62" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
 *                   <sequence minOccurs="0">
 *                     <element name="P_63" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrNIP"/>
 *                     <element name="P_64" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
 *                     <element name="P_65" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
 *                     <element name="P_66" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TKodStrefy"/>
 *                     <element name="P_67" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
 *                   </sequence>
 *                   <sequence minOccurs="0">
 *                     <element name="P_68" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrNIP"/>
 *                     <element name="P_69" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
 *                     <element name="P_70" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
 *                     <element name="P_71" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TKodStrefy"/>
 *                     <element name="P_72" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
 *                   </sequence>
 *                   <element name="P_73" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNaturalny">
 *                         <maxInclusive value="99"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="P_74" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNaturalny">
 *                         <maxInclusive value="99"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Zalaczniki" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element ref="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSEA/}Zalacznik_SSE_A" maxOccurs="99" minOccurs="0"/>
 *                   <element ref="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSERA/}Zalacznik_SSE-R_A" maxOccurs="99" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naglowek",
    "podmiot1",
    "pozycjeSzczegolowe",
    "zalaczniki"
})
@XmlRootElement(name = "Zalacznik_SSE-R")
public class ZalacznikSSER {

    @XmlElement(name = "Naglowek", required = true)
    protected TNaglowekSSER naglowek;
    @XmlElement(name = "Podmiot1", required = true)
    protected Podmiot1 podmiot1;
    /**
     * Ustalenie dopuszczalnej wielkości pomocy publicznej dla przedsiębiorców, o których mowa w art. 5 ust. 2 ustawy, rozliczenie podatku stanowiącego źródło finansowania przedsiębiorców, o których mowa w art. 5 ust. 2 ustawy, obliczenie podatku, który podlegałby zapłacie przy uwzględnieniu zwolnień wynikających z art. 12 ustawy o SSE w brzmieniu obowiązującym w dniu 31 grudnia 2000 r., kwota podatku podlegająca przekazaniu na rachunek funduszu strefowego, wykaz udziałów podatnika w spółkach
     * 
     */
    @XmlElement(name = "PozycjeSzczegolowe", required = true)
    protected PozycjeSzczegolowe pozycjeSzczegolowe;
    @XmlElement(name = "Zalaczniki")
    protected Zalaczniki zalaczniki;

    /**
     * Gets the value of the naglowek property.
     * 
     * @return
     *     possible object is
     *     {@link TNaglowekSSER }
     *     
     */
    public TNaglowekSSER getNaglowek() {
        return naglowek;
    }

    /**
     * Sets the value of the naglowek property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNaglowekSSER }
     *     
     */
    public void setNaglowek(TNaglowekSSER value) {
        this.naglowek = value;
    }

    /**
     * Gets the value of the podmiot1 property.
     * 
     * @return
     *     possible object is
     *     {@link Podmiot1 }
     *     
     */
    public Podmiot1 getPodmiot1() {
        return podmiot1;
    }

    /**
     * Sets the value of the podmiot1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Podmiot1 }
     *     
     */
    public void setPodmiot1( Podmiot1 value) {
        this.podmiot1 = value;
    }

    /**
     * Ustalenie dopuszczalnej wielkości pomocy publicznej dla przedsiębiorców, o których mowa w art. 5 ust. 2 ustawy, rozliczenie podatku stanowiącego źródło finansowania przedsiębiorców, o których mowa w art. 5 ust. 2 ustawy, obliczenie podatku, który podlegałby zapłacie przy uwzględnieniu zwolnień wynikających z art. 12 ustawy o SSE w brzmieniu obowiązującym w dniu 31 grudnia 2000 r., kwota podatku podlegająca przekazaniu na rachunek funduszu strefowego, wykaz udziałów podatnika w spółkach
     * 
     * @return
     *     possible object is
     *     {@link PozycjeSzczegolowe }
     *     
     */
    public PozycjeSzczegolowe getPozycjeSzczegolowe() {
        return pozycjeSzczegolowe;
    }

    /**
     * Sets the value of the pozycjeSzczegolowe property.
     * 
     * @param value
     *     allowed object is
     *     {@link PozycjeSzczegolowe }
     *     
     * @see #getPozycjeSzczegolowe()
     */
    public void setPozycjeSzczegolowe( PozycjeSzczegolowe value) {
        this.pozycjeSzczegolowe = value;
    }

    /**
     * Gets the value of the zalaczniki property.
     * 
     * @return
     *     possible object is
     *     {@link Zalaczniki }
     *     
     */
    public Zalaczniki getZalaczniki() {
        return zalaczniki;
    }

    /**
     * Sets the value of the zalaczniki property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zalaczniki }
     *     
     */
    public void setZalaczniki( Zalaczniki value) {
        this.zalaczniki = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TPodmiotDowolnyBezAdresu">
     *       <attribute name="rola" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Składający" />
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Podmiot1
        extends TPodmiotDowolnyBezAdresu
    {

        @XmlAttribute(name = "rola", required = true)
        protected String rola;

        /**
         * Gets the value of the rola property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRola() {
            if (rola == null) {
                return "Sk\u0142adaj\u0105cy";
            } else {
                return rola;
            }
        }

        /**
         * Sets the value of the rola property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRola(String value) {
            this.rola = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="P_7" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1_2"/>
     *         <element name="P_8" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1_3"/>
     *         <element name="P_9" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TKodStrefy"/>
     *         <element name="P_10" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy" minOccurs="0"/>
     *         <element name="P_11" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TData">
     *               <minInclusive value="1995-10-01"/>
     *               <maxInclusive value="2000-12-31"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="P_12" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TData" minOccurs="0"/>
     *         <element name="P_13" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TData">
     *               <minInclusive value="2004-05-01"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="P_14" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TWybor1_2"/>
     *         <element name="P_15" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_16" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_17" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_18" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_19" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <sequence minOccurs="0">
     *           <element name="P_20A" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
     *           <element name="P_20" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_21" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_22" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         </sequence>
     *         <element name="P_23" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_24" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_25" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <sequence>
     *           <element name="P_26" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_27" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_28" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_29" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *           <element name="P_30" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         </sequence>
     *         <element name="P_31" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
     *         <element name="P_32" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
     *         <element name="P_33" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_34" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_35" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_36" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_37" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_38" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_39" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_40" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_41" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_42" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_43" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_44" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <choice minOccurs="0">
     *           <element name="P_45" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
     *           <element name="P_46" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         </choice>
     *         <element name="P_47" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_48" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_49" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_50" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_51" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_52" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_53" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_54" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_55" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_56" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwotaCNieujemna"/>
     *         <element name="P_57" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_58" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_59" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna" minOccurs="0"/>
     *         <element name="P_60" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_61" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <element name="P_62" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TKwota2Nieujemna"/>
     *         <sequence minOccurs="0">
     *           <element name="P_63" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrNIP"/>
     *           <element name="P_64" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
     *           <element name="P_65" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
     *           <element name="P_66" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TKodStrefy"/>
     *           <element name="P_67" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
     *         </sequence>
     *         <sequence minOccurs="0">
     *           <element name="P_68" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNrNIP"/>
     *           <element name="P_69" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TProcentowy"/>
     *           <element name="P_70" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
     *           <element name="P_71" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSER/}TKodStrefy"/>
     *           <element name="P_72" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TZnakowy"/>
     *         </sequence>
     *         <element name="P_73" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNaturalny">
     *               <maxInclusive value="99"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="P_74" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/}TNaturalny">
     *               <maxInclusive value="99"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p7",
        "p8",
        "p9",
        "p10",
        "p11",
        "p12",
        "p13",
        "p14",
        "p15",
        "p16",
        "p17",
        "p18",
        "p19",
        "p20A",
        "p20",
        "p21",
        "p22",
        "p23",
        "p24",
        "p25",
        "p26",
        "p27",
        "p28",
        "p29",
        "p30",
        "p31",
        "p32",
        "p33",
        "p34",
        "p35",
        "p36",
        "p37",
        "p38",
        "p39",
        "p40",
        "p41",
        "p42",
        "p43",
        "p44",
        "p45",
        "p46",
        "p47",
        "p48",
        "p49",
        "p50",
        "p51",
        "p52",
        "p53",
        "p54",
        "p55",
        "p56",
        "p57",
        "p58",
        "p59",
        "p60",
        "p61",
        "p62",
        "p63",
        "p64",
        "p65",
        "p66",
        "p67",
        "p68",
        "p69",
        "p70",
        "p71",
        "p72",
        "p73",
        "p74"
    })
    public static class PozycjeSzczegolowe {

        /**
         * Składający informację jest podatnikiem podatku dochodowego od osób: 1 - fizycznych, 2 - prawnych
         * 
         */
        @XmlElement(name = "P_7")
        protected byte p7;
        /**
         * Składana informacja dotyczy przedsiębiorcy będącego w dniu wejścia w życie ustawy: 1 - małym przesiębiorcą, 2 - średnim przesiębiorcą, 3 - dużym przesiębiorcą
         * 
         */
        @XmlElement(name = "P_8")
        protected byte p8;
        /**
         * Kod strefy, na której terenie podatnik prowadzi działalność gospodarczą
         * 
         */
        @XmlElement(name = "P_9")
        protected byte p9;
        /**
         * Numer zezwolenia
         * 
         */
        @XmlElement(name = "P_10")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String p10;
        /**
         * Data wydania zezwolenia
         * 
         */
        @XmlElement(name = "P_11")
        protected XMLGregorianCalendar p11;
        /**
         * Data rozpoczęcia działalności
         * 
         */
        @XmlElement(name = "P_12")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar p12;
        /**
         * Data zmiany zezwolenia
         * 
         */
        @XmlElement(name = "P_13")
        protected XMLGregorianCalendar p13;
        /**
         * Podatnik prowadzi działalność w sektorze motoryzacyjnym w rozumieniu art. 5 ust. 5 ustawy: 1 - tak, 2 - nie
         * 
         */
        @XmlElement(name = "P_14")
        protected byte p14;
        /**
         * Zwolnienia i preferencje w podatku dochodowym w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy
         * 
         */
        @XmlElement(name = "P_15")
        protected BigDecimal p15;
        /**
         * Zwolnienia i preferencje w podatku dochodowym w roku podatkowym
         * 
         */
        @XmlElement(name = "P_16")
        protected BigDecimal p16;
        /**
         * Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy
         * 
         */
        @XmlElement(name = "P_17")
        protected BigDecimal p17;
        /**
         * Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w roku podatkowym
         * 
         */
        @XmlElement(name = "P_18")
        protected BigDecimal p18;
        /**
         * Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w roku, w którym składana jest informacja, do dnia jej złożenia
         * 
         */
        @XmlElement(name = "P_19")
        protected BigDecimal p19;
        /**
         * Inne
         * 
         */
        @XmlElement(name = "P_20A")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String p20A;
        /**
         * Inne w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy
         * 
         */
        @XmlElement(name = "P_20")
        protected BigDecimal p20;
        /**
         * Inne w roku podatkowym
         * 
         */
        @XmlElement(name = "P_21")
        protected BigDecimal p21;
        /**
         * Inne w roku, w którym składana jest informacja, do dnia jej złożenia
         * 
         */
        @XmlElement(name = "P_22")
        protected BigDecimal p22;
        /**
         * Łączna wartość pomocy w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy
         * 
         */
        @XmlElement(name = "P_23", required = true)
        protected BigDecimal p23;
        /**
         * Łączna wartość pomocy w roku podatkowym
         * 
         */
        @XmlElement(name = "P_24", required = true)
        protected BigDecimal p24;
        /**
         * Łączna wartość pomocy w roku, w którym składana jest informacja, do dnia jej złożenia
         * 
         */
        @XmlElement(name = "P_25", required = true)
        protected BigDecimal p25;
        /**
         * Zakup albo wytworzenie we własnym zakresie środków trwałych lub ich spłata określona w umowie leasingu lub innej umowie o podobnym charakterze, z wyłączeniem środków transportu nabywanych przez przedsiębiorcę prowadzącego działalność gospodarczą w sektorze transportu, pod warunkiem zaliczenia ich - zgodnie z odrębnymi przepisami - do składników majątku podatnika
         * 
         */
        @XmlElement(name = "P_26")
        protected BigDecimal p26;
        /**
         * Rozbudowa lub modernizacja istniejących środków trwałych, zaliczonych do wartości początkowej tych środków trwałych zgodnie z przepisami o podatku dochodowym
         * 
         */
        @XmlElement(name = "P_27")
        protected BigDecimal p27;
        /**
         * Wytworzenie lub zakup wartości niematerialnych i prawnych związanych z uzyskaniem patentów, licencji operacyjnych bądź opatentowanych licencji typu know-how
         * 
         */
        @XmlElement(name = "P_28")
        protected BigDecimal p28;
        /**
         * Wkłady niepieniężne wniesione do przedsiębiorstwa przed dniem 01.05.2004 r., spełniające kryteria kosztów kwalifikujących się do objęcia pomocą - zgodnie z odrębnymi przepisami
         * 
         */
        @XmlElement(name = "P_29")
        protected BigDecimal p29;
        /**
         * Łączna wartość kosztów
         * 
         */
        @XmlElement(name = "P_30", required = true)
        protected BigDecimal p30;
        /**
         * Osiągnięta intensywność pomocy
         * 
         */
        @XmlElement(name = "P_31", required = true)
        protected BigDecimal p31;
        /**
         * Maksymalna intensywność pomocy właściwa dla danego przedsiębiorcy, którego dotyczy informacja, określona w art. 5 ust. 2 i 8 ustawy (w przypadku wspólników spółek osobowych, w tym spółek cywilnych maksymalną intensywność pomocy należy podać proporcjonalnie do udziałów w zyskach spółki)
         * 
         */
        @XmlElement(name = "P_32", required = true)
        protected BigDecimal p32;
        /**
         * Maksymalna wartość pomocy
         * 
         */
        @XmlElement(name = "P_33", required = true)
        protected BigDecimal p33;
        /**
         * Wartość pomocy do wykorzystania
         * 
         */
        @XmlElement(name = "P_34", required = true)
        protected BigDecimal p34;
        /**
         * Dochód osiągnięty z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r. w okresie, za który składana jest niniejsza informacja
         * 
         */
        @XmlElement(name = "P_35", required = true)
        protected BigDecimal p35;
        /**
         * Równowartość strat poniesionych na tej działalności nieodliczonych w informacjach SSE-R składanych za poprzednie lata podatkowe. Wartość wykazana w poz. 36 nie może przekroczyć wartości wykazanej w poz. 35
         * 
         */
        @XmlElement(name = "P_36", required = true)
        protected BigDecimal p36;
        /**
         * Dochód osiągnięty w roku objętym informacją, z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r. po odliczeniu straty, ustalony w celu określenia wielkości pomocy
         * 
         */
        @XmlElement(name = "P_37", required = true)
        protected BigDecimal p37;
        /**
         * Podatek od dochodu wykazanego w poz. 37 wyliczony w celu ustalenia wielkości pomocy publicznej
         * 
         */
        @XmlElement(name = "P_38", required = true)
        protected BigDecimal p38;
        /**
         * Dopuszczalna kwota udzielenia pomocy po uwzględnieniu rozliczenia podatku za dany rok podatkowy
         * 
         */
        @XmlElement(name = "P_39", required = true)
        protected BigDecimal p39;
        /**
         * Kwota podatku przekraczająca dopuszczalną intensywność pomocy
         * 
         */
        @XmlElement(name = "P_40", required = true)
        protected BigDecimal p40;
        /**
         * Podatek od dochodu zwolnionego z tytułu prowadzenia działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.
         * 
         */
        @XmlElement(name = "P_41", required = true)
        protected BigDecimal p41;
        /**
         * Kwota dochodu zwolnionego z tytułu prowadzenia działalności na terenie strefy na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.
         * 
         */
        @XmlElement(name = "P_42", required = true)
        protected BigDecimal p42;
        /**
         * Dochód osiągnięty w roku podatkowym, w zakresie nieobjętym rozliczeniem pomocy publicznej (zwolnieniem), o którym mowa w części D. W przypadku małego lub średniego przedsiębiorcy należy wpisać kwotę dochodu osiągniętego z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r., w okresie, za który składana jest niniejsza informacja
         * 
         */
        @XmlElement(name = "P_43")
        protected BigDecimal p43;
        /**
         * Strata poniesiona w roku podatkowym
         * 
         */
        @XmlElement(name = "P_44")
        protected BigDecimal p44;
        /**
         * Podać procentowo jaka część dochodu byłaby zwolniona, jeżeli zwolnienie zostało określone procentowo
         * 
         */
        @XmlElement(name = "P_45")
        protected BigDecimal p45;
        /**
         * Podać kwotowo pełną kwotę zwolnienia
         * 
         */
        @XmlElement(name = "P_46")
        protected BigDecimal p46;
        /**
         * Dochód, jaki byłby zwolniony od podatku na podstawie przepisów o specjalnych strefach ekonomicznych w brzmieniu obowiązującym w dniu 31 grudnia 2000 r.
         * 
         */
        @XmlElement(name = "P_47")
        protected BigDecimal p47;
        /**
         * Dochód, jaki nie podlegałby zwolnieniu od podatku
         * 
         */
        @XmlElement(name = "P_48")
        protected BigDecimal p48;
        /**
         * Strata nieprzypisana do części źródła dochodu zwolnionej od podatku
         * 
         */
        @XmlElement(name = "P_49")
        protected BigDecimal p49;
        /**
         * Dochody z działalności innej niż wymieniona w części E.1
         * 
         */
        @XmlElement(name = "P_50")
        protected BigDecimal p50;
        /**
         * Straty z działalności innej niż wymieniona w części E.1
         * 
         */
        @XmlElement(name = "P_51")
        protected BigDecimal p51;
        /**
         * Dochód
         * 
         */
        @XmlElement(name = "P_52", required = true)
        protected BigDecimal p52;
        /**
         * Strata przed zmniejszeniami i zwiększeniami
         * 
         */
        @XmlElement(name = "P_53")
        protected BigDecimal p53;
        /**
         * Ulgi od dochodu/przychodu
         * 
         */
        @XmlElement(name = "P_54")
        protected BigDecimal p54;
        /**
         * Kwota zwiększająca podstawę opodatkowania/zmniejszająca stratę
         * 
         */
        @XmlElement(name = "P_55")
        protected BigDecimal p55;
        /**
         * Podstawa opodatkowania
         * 
         */
        @XmlElement(name = "P_56", required = true)
        protected BigInteger p56;
        /**
         * Strata
         * 
         */
        @XmlElement(name = "P_57")
        protected BigDecimal p57;
        /**
         * Podatek obliczony od podstawy opodatkowania z poz. 56
         * 
         */
        @XmlElement(name = "P_58", required = true)
        protected BigDecimal p58;
        /**
         * Odliczenia od podatku
         * 
         */
        @XmlElement(name = "P_59")
        protected BigDecimal p59;
        /**
         * Kwota należnego i zapłaconego podatku dochodowego w terminie złożenia deklaracji o wysokości osiągniętego dochodu, do której informacja stanowi załącznik
         * 
         */
        @XmlElement(name = "P_60", required = true)
        protected BigDecimal p60;
        /**
         * Kwota podatku, która podlegałaby zapłacie przy uwzględnieniu zwolnień podatkowych wynikających z art. 12 ustawy o SSE w brzmieniu obowiązującym w dniu 31 grudnia 2000 r.
         * 
         */
        @XmlElement(name = "P_61", required = true)
        protected BigDecimal p61;
        /**
         * Kwota podatku podlegająca zgromadzeniu na rachunku Funduszu Strefowego za rok podatkowy
         * 
         */
        @XmlElement(name = "P_62", required = true)
        protected BigDecimal p62;
        /**
         * Identyfikator podatkowy NIP spółki
         * 
         */
        @XmlElement(name = "P_63")
        protected String p63;
        /**
         * Udział w %
         * 
         */
        @XmlElement(name = "P_64")
        protected BigDecimal p64;
        /**
         * Nazwa pełna
         * 
         */
        @XmlElement(name = "P_65")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String p65;
        /**
         * Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.
         * 
         */
        @XmlElement(name = "P_66")
        protected Byte p66;
        /**
         * Adres siedziby spółki
         * 
         */
        @XmlElement(name = "P_67")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String p67;
        /**
         * Identyfikator podatkowy NIP spółki
         * 
         */
        @XmlElement(name = "P_68")
        protected String p68;
        /**
         * Udział w %
         * 
         */
        @XmlElement(name = "P_69")
        protected BigDecimal p69;
        /**
         * Nazwa pełna
         * 
         */
        @XmlElement(name = "P_70")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String p70;
        /**
         * Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.
         * 
         */
        @XmlElement(name = "P_71")
        protected Byte p71;
        /**
         * Adres siedziby spółki
         * 
         */
        @XmlElement(name = "P_72")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String p72;
        /**
         * Informacja o załącznikach SSE/A
         * 
         */
        @XmlElement(name = "P_73")
        protected Integer p73;
        /**
         * Informacja o załącznikach SSE-R/A
         * 
         */
        @XmlElement(name = "P_74")
        protected Integer p74;

        /**
         * Składający informację jest podatnikiem podatku dochodowego od osób: 1 - fizycznych, 2 - prawnych
         * 
         */
        public byte getP7() {
            return p7;
        }

        /**
         * Sets the value of the p7 property.
         * 
         */
        public void setP7(byte value) {
            this.p7 = value;
        }

        /**
         * Składana informacja dotyczy przedsiębiorcy będącego w dniu wejścia w życie ustawy: 1 - małym przesiębiorcą, 2 - średnim przesiębiorcą, 3 - dużym przesiębiorcą
         * 
         */
        public byte getP8() {
            return p8;
        }

        /**
         * Sets the value of the p8 property.
         * 
         */
        public void setP8(byte value) {
            this.p8 = value;
        }

        /**
         * Kod strefy, na której terenie podatnik prowadzi działalność gospodarczą
         * 
         */
        public byte getP9() {
            return p9;
        }

        /**
         * Sets the value of the p9 property.
         * 
         */
        public void setP9(byte value) {
            this.p9 = value;
        }

        /**
         * Numer zezwolenia
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP10() {
            return p10;
        }

        /**
         * Sets the value of the p10 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getP10()
         */
        public void setP10(String value) {
            this.p10 = value;
        }

        /**
         * Data wydania zezwolenia
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getP11() {
            return p11;
        }

        /**
         * Sets the value of the p11 property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getP11()
         */
        public void setP11(XMLGregorianCalendar value) {
            this.p11 = value;
        }

        /**
         * Data rozpoczęcia działalności
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getP12() {
            return p12;
        }

        /**
         * Sets the value of the p12 property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getP12()
         */
        public void setP12(XMLGregorianCalendar value) {
            this.p12 = value;
        }

        /**
         * Data zmiany zezwolenia
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getP13() {
            return p13;
        }

        /**
         * Sets the value of the p13 property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getP13()
         */
        public void setP13(XMLGregorianCalendar value) {
            this.p13 = value;
        }

        /**
         * Podatnik prowadzi działalność w sektorze motoryzacyjnym w rozumieniu art. 5 ust. 5 ustawy: 1 - tak, 2 - nie
         * 
         */
        public byte getP14() {
            return p14;
        }

        /**
         * Sets the value of the p14 property.
         * 
         */
        public void setP14(byte value) {
            this.p14 = value;
        }

        /**
         * Zwolnienia i preferencje w podatku dochodowym w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP15() {
            return p15;
        }

        /**
         * Sets the value of the p15 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP15()
         */
        public void setP15(BigDecimal value) {
            this.p15 = value;
        }

        /**
         * Zwolnienia i preferencje w podatku dochodowym w roku podatkowym
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP16() {
            return p16;
        }

        /**
         * Sets the value of the p16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP16()
         */
        public void setP16(BigDecimal value) {
            this.p16 = value;
        }

        /**
         * Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP17() {
            return p17;
        }

        /**
         * Sets the value of the p17 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP17()
         */
        public void setP17(BigDecimal value) {
            this.p17 = value;
        }

        /**
         * Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w roku podatkowym
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP18() {
            return p18;
        }

        /**
         * Sets the value of the p18 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP18()
         */
        public void setP18(BigDecimal value) {
            this.p18 = value;
        }

        /**
         * Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w roku, w którym składana jest informacja, do dnia jej złożenia
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP19() {
            return p19;
        }

        /**
         * Sets the value of the p19 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP19()
         */
        public void setP19(BigDecimal value) {
            this.p19 = value;
        }

        /**
         * Inne
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP20A() {
            return p20A;
        }

        /**
         * Sets the value of the p20A property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getP20A()
         */
        public void setP20A(String value) {
            this.p20A = value;
        }

        /**
         * Inne w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP20() {
            return p20;
        }

        /**
         * Sets the value of the p20 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP20()
         */
        public void setP20(BigDecimal value) {
            this.p20 = value;
        }

        /**
         * Inne w roku podatkowym
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP21() {
            return p21;
        }

        /**
         * Sets the value of the p21 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP21()
         */
        public void setP21(BigDecimal value) {
            this.p21 = value;
        }

        /**
         * Inne w roku, w którym składana jest informacja, do dnia jej złożenia
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP22() {
            return p22;
        }

        /**
         * Sets the value of the p22 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP22()
         */
        public void setP22(BigDecimal value) {
            this.p22 = value;
        }

        /**
         * Łączna wartość pomocy w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP23() {
            return p23;
        }

        /**
         * Sets the value of the p23 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP23()
         */
        public void setP23(BigDecimal value) {
            this.p23 = value;
        }

        /**
         * Łączna wartość pomocy w roku podatkowym
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP24() {
            return p24;
        }

        /**
         * Sets the value of the p24 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP24()
         */
        public void setP24(BigDecimal value) {
            this.p24 = value;
        }

        /**
         * Łączna wartość pomocy w roku, w którym składana jest informacja, do dnia jej złożenia
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP25() {
            return p25;
        }

        /**
         * Sets the value of the p25 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP25()
         */
        public void setP25(BigDecimal value) {
            this.p25 = value;
        }

        /**
         * Zakup albo wytworzenie we własnym zakresie środków trwałych lub ich spłata określona w umowie leasingu lub innej umowie o podobnym charakterze, z wyłączeniem środków transportu nabywanych przez przedsiębiorcę prowadzącego działalność gospodarczą w sektorze transportu, pod warunkiem zaliczenia ich - zgodnie z odrębnymi przepisami - do składników majątku podatnika
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP26() {
            return p26;
        }

        /**
         * Sets the value of the p26 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP26()
         */
        public void setP26(BigDecimal value) {
            this.p26 = value;
        }

        /**
         * Rozbudowa lub modernizacja istniejących środków trwałych, zaliczonych do wartości początkowej tych środków trwałych zgodnie z przepisami o podatku dochodowym
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP27() {
            return p27;
        }

        /**
         * Sets the value of the p27 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP27()
         */
        public void setP27(BigDecimal value) {
            this.p27 = value;
        }

        /**
         * Wytworzenie lub zakup wartości niematerialnych i prawnych związanych z uzyskaniem patentów, licencji operacyjnych bądź opatentowanych licencji typu know-how
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP28() {
            return p28;
        }

        /**
         * Sets the value of the p28 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP28()
         */
        public void setP28(BigDecimal value) {
            this.p28 = value;
        }

        /**
         * Wkłady niepieniężne wniesione do przedsiębiorstwa przed dniem 01.05.2004 r., spełniające kryteria kosztów kwalifikujących się do objęcia pomocą - zgodnie z odrębnymi przepisami
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP29() {
            return p29;
        }

        /**
         * Sets the value of the p29 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP29()
         */
        public void setP29(BigDecimal value) {
            this.p29 = value;
        }

        /**
         * Łączna wartość kosztów
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP30() {
            return p30;
        }

        /**
         * Sets the value of the p30 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP30()
         */
        public void setP30(BigDecimal value) {
            this.p30 = value;
        }

        /**
         * Osiągnięta intensywność pomocy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP31() {
            return p31;
        }

        /**
         * Sets the value of the p31 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP31()
         */
        public void setP31(BigDecimal value) {
            this.p31 = value;
        }

        /**
         * Maksymalna intensywność pomocy właściwa dla danego przedsiębiorcy, którego dotyczy informacja, określona w art. 5 ust. 2 i 8 ustawy (w przypadku wspólników spółek osobowych, w tym spółek cywilnych maksymalną intensywność pomocy należy podać proporcjonalnie do udziałów w zyskach spółki)
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP32() {
            return p32;
        }

        /**
         * Sets the value of the p32 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP32()
         */
        public void setP32(BigDecimal value) {
            this.p32 = value;
        }

        /**
         * Maksymalna wartość pomocy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP33() {
            return p33;
        }

        /**
         * Sets the value of the p33 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP33()
         */
        public void setP33(BigDecimal value) {
            this.p33 = value;
        }

        /**
         * Wartość pomocy do wykorzystania
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP34() {
            return p34;
        }

        /**
         * Sets the value of the p34 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP34()
         */
        public void setP34(BigDecimal value) {
            this.p34 = value;
        }

        /**
         * Dochód osiągnięty z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r. w okresie, za który składana jest niniejsza informacja
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP35() {
            return p35;
        }

        /**
         * Sets the value of the p35 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP35()
         */
        public void setP35(BigDecimal value) {
            this.p35 = value;
        }

        /**
         * Równowartość strat poniesionych na tej działalności nieodliczonych w informacjach SSE-R składanych za poprzednie lata podatkowe. Wartość wykazana w poz. 36 nie może przekroczyć wartości wykazanej w poz. 35
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP36() {
            return p36;
        }

        /**
         * Sets the value of the p36 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP36()
         */
        public void setP36(BigDecimal value) {
            this.p36 = value;
        }

        /**
         * Dochód osiągnięty w roku objętym informacją, z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r. po odliczeniu straty, ustalony w celu określenia wielkości pomocy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP37() {
            return p37;
        }

        /**
         * Sets the value of the p37 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP37()
         */
        public void setP37(BigDecimal value) {
            this.p37 = value;
        }

        /**
         * Podatek od dochodu wykazanego w poz. 37 wyliczony w celu ustalenia wielkości pomocy publicznej
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP38() {
            return p38;
        }

        /**
         * Sets the value of the p38 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP38()
         */
        public void setP38(BigDecimal value) {
            this.p38 = value;
        }

        /**
         * Dopuszczalna kwota udzielenia pomocy po uwzględnieniu rozliczenia podatku za dany rok podatkowy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP39() {
            return p39;
        }

        /**
         * Sets the value of the p39 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP39()
         */
        public void setP39(BigDecimal value) {
            this.p39 = value;
        }

        /**
         * Kwota podatku przekraczająca dopuszczalną intensywność pomocy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP40() {
            return p40;
        }

        /**
         * Sets the value of the p40 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP40()
         */
        public void setP40(BigDecimal value) {
            this.p40 = value;
        }

        /**
         * Podatek od dochodu zwolnionego z tytułu prowadzenia działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP41() {
            return p41;
        }

        /**
         * Sets the value of the p41 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP41()
         */
        public void setP41(BigDecimal value) {
            this.p41 = value;
        }

        /**
         * Kwota dochodu zwolnionego z tytułu prowadzenia działalności na terenie strefy na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP42() {
            return p42;
        }

        /**
         * Sets the value of the p42 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP42()
         */
        public void setP42(BigDecimal value) {
            this.p42 = value;
        }

        /**
         * Dochód osiągnięty w roku podatkowym, w zakresie nieobjętym rozliczeniem pomocy publicznej (zwolnieniem), o którym mowa w części D. W przypadku małego lub średniego przedsiębiorcy należy wpisać kwotę dochodu osiągniętego z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r., w okresie, za który składana jest niniejsza informacja
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP43() {
            return p43;
        }

        /**
         * Sets the value of the p43 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP43()
         */
        public void setP43(BigDecimal value) {
            this.p43 = value;
        }

        /**
         * Strata poniesiona w roku podatkowym
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP44() {
            return p44;
        }

        /**
         * Sets the value of the p44 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP44()
         */
        public void setP44(BigDecimal value) {
            this.p44 = value;
        }

        /**
         * Podać procentowo jaka część dochodu byłaby zwolniona, jeżeli zwolnienie zostało określone procentowo
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP45() {
            return p45;
        }

        /**
         * Sets the value of the p45 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP45()
         */
        public void setP45(BigDecimal value) {
            this.p45 = value;
        }

        /**
         * Podać kwotowo pełną kwotę zwolnienia
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP46() {
            return p46;
        }

        /**
         * Sets the value of the p46 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP46()
         */
        public void setP46(BigDecimal value) {
            this.p46 = value;
        }

        /**
         * Dochód, jaki byłby zwolniony od podatku na podstawie przepisów o specjalnych strefach ekonomicznych w brzmieniu obowiązującym w dniu 31 grudnia 2000 r.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP47() {
            return p47;
        }

        /**
         * Sets the value of the p47 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP47()
         */
        public void setP47(BigDecimal value) {
            this.p47 = value;
        }

        /**
         * Dochód, jaki nie podlegałby zwolnieniu od podatku
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP48() {
            return p48;
        }

        /**
         * Sets the value of the p48 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP48()
         */
        public void setP48(BigDecimal value) {
            this.p48 = value;
        }

        /**
         * Strata nieprzypisana do części źródła dochodu zwolnionej od podatku
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP49() {
            return p49;
        }

        /**
         * Sets the value of the p49 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP49()
         */
        public void setP49(BigDecimal value) {
            this.p49 = value;
        }

        /**
         * Dochody z działalności innej niż wymieniona w części E.1
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP50() {
            return p50;
        }

        /**
         * Sets the value of the p50 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP50()
         */
        public void setP50(BigDecimal value) {
            this.p50 = value;
        }

        /**
         * Straty z działalności innej niż wymieniona w części E.1
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP51() {
            return p51;
        }

        /**
         * Sets the value of the p51 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP51()
         */
        public void setP51(BigDecimal value) {
            this.p51 = value;
        }

        /**
         * Dochód
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP52() {
            return p52;
        }

        /**
         * Sets the value of the p52 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP52()
         */
        public void setP52(BigDecimal value) {
            this.p52 = value;
        }

        /**
         * Strata przed zmniejszeniami i zwiększeniami
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP53() {
            return p53;
        }

        /**
         * Sets the value of the p53 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP53()
         */
        public void setP53(BigDecimal value) {
            this.p53 = value;
        }

        /**
         * Ulgi od dochodu/przychodu
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP54() {
            return p54;
        }

        /**
         * Sets the value of the p54 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP54()
         */
        public void setP54(BigDecimal value) {
            this.p54 = value;
        }

        /**
         * Kwota zwiększająca podstawę opodatkowania/zmniejszająca stratę
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP55() {
            return p55;
        }

        /**
         * Sets the value of the p55 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP55()
         */
        public void setP55(BigDecimal value) {
            this.p55 = value;
        }

        /**
         * Podstawa opodatkowania
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getP56() {
            return p56;
        }

        /**
         * Sets the value of the p56 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getP56()
         */
        public void setP56(BigInteger value) {
            this.p56 = value;
        }

        /**
         * Strata
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP57() {
            return p57;
        }

        /**
         * Sets the value of the p57 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP57()
         */
        public void setP57(BigDecimal value) {
            this.p57 = value;
        }

        /**
         * Podatek obliczony od podstawy opodatkowania z poz. 56
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP58() {
            return p58;
        }

        /**
         * Sets the value of the p58 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP58()
         */
        public void setP58(BigDecimal value) {
            this.p58 = value;
        }

        /**
         * Odliczenia od podatku
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP59() {
            return p59;
        }

        /**
         * Sets the value of the p59 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP59()
         */
        public void setP59(BigDecimal value) {
            this.p59 = value;
        }

        /**
         * Kwota należnego i zapłaconego podatku dochodowego w terminie złożenia deklaracji o wysokości osiągniętego dochodu, do której informacja stanowi załącznik
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP60() {
            return p60;
        }

        /**
         * Sets the value of the p60 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP60()
         */
        public void setP60(BigDecimal value) {
            this.p60 = value;
        }

        /**
         * Kwota podatku, która podlegałaby zapłacie przy uwzględnieniu zwolnień podatkowych wynikających z art. 12 ustawy o SSE w brzmieniu obowiązującym w dniu 31 grudnia 2000 r.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP61() {
            return p61;
        }

        /**
         * Sets the value of the p61 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP61()
         */
        public void setP61(BigDecimal value) {
            this.p61 = value;
        }

        /**
         * Kwota podatku podlegająca zgromadzeniu na rachunku Funduszu Strefowego za rok podatkowy
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP62() {
            return p62;
        }

        /**
         * Sets the value of the p62 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP62()
         */
        public void setP62(BigDecimal value) {
            this.p62 = value;
        }

        /**
         * Identyfikator podatkowy NIP spółki
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP63() {
            return p63;
        }

        /**
         * Sets the value of the p63 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getP63()
         */
        public void setP63(String value) {
            this.p63 = value;
        }

        /**
         * Udział w %
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP64() {
            return p64;
        }

        /**
         * Sets the value of the p64 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP64()
         */
        public void setP64(BigDecimal value) {
            this.p64 = value;
        }

        /**
         * Nazwa pełna
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP65() {
            return p65;
        }

        /**
         * Sets the value of the p65 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getP65()
         */
        public void setP65(String value) {
            this.p65 = value;
        }

        /**
         * Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP66() {
            return p66;
        }

        /**
         * Sets the value of the p66 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP66()
         */
        public void setP66(Byte value) {
            this.p66 = value;
        }

        /**
         * Adres siedziby spółki
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP67() {
            return p67;
        }

        /**
         * Sets the value of the p67 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getP67()
         */
        public void setP67(String value) {
            this.p67 = value;
        }

        /**
         * Identyfikator podatkowy NIP spółki
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP68() {
            return p68;
        }

        /**
         * Sets the value of the p68 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getP68()
         */
        public void setP68(String value) {
            this.p68 = value;
        }

        /**
         * Udział w %
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP69() {
            return p69;
        }

        /**
         * Sets the value of the p69 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getP69()
         */
        public void setP69(BigDecimal value) {
            this.p69 = value;
        }

        /**
         * Nazwa pełna
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP70() {
            return p70;
        }

        /**
         * Sets the value of the p70 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getP70()
         */
        public void setP70(String value) {
            this.p70 = value;
        }

        /**
         * Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getP71() {
            return p71;
        }

        /**
         * Sets the value of the p71 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         * @see #getP71()
         */
        public void setP71(Byte value) {
            this.p71 = value;
        }

        /**
         * Adres siedziby spółki
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP72() {
            return p72;
        }

        /**
         * Sets the value of the p72 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getP72()
         */
        public void setP72(String value) {
            this.p72 = value;
        }

        /**
         * Informacja o załącznikach SSE/A
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getP73() {
            return p73;
        }

        /**
         * Sets the value of the p73 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         * @see #getP73()
         */
        public void setP73(Integer value) {
            this.p73 = value;
        }

        /**
         * Informacja o załącznikach SSE-R/A
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getP74() {
            return p74;
        }

        /**
         * Sets the value of the p74 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         * @see #getP74()
         */
        public void setP74(Integer value) {
            this.p74 = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element ref="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSEA/}Zalacznik_SSE_A" maxOccurs="99" minOccurs="0"/>
     *         <element ref="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSERA/}Zalacznik_SSE-R_A" maxOccurs="99" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zalacznikSSEA",
        "zalacznikSSERA"
    })
    public static class Zalaczniki {

        /**
         * WYKAZ UDZIAŁÓW W SPÓŁKACH
         * 
         */
        @XmlElement(name = "Zalacznik_SSE_A", namespace = "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSEA/")
        protected List<ZalacznikSSEA> zalacznikSSEA;
        /**
         * ROZLICZENIE ZDYSKONTOWANEJ WARTOŚCI UDZIELONEJ POMOCY PUBLICZNEJ I KOSZTÓW KWALIFIKUJĄCYCH SIĘ DO OBJĘCIA TĄ POMOCĄ
         * 
         */
        @XmlElement(name = "Zalacznik_SSE-R_A", namespace = "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2024/02/05/eD/SSERA/")
        protected List<ZalacznikSSERA> zalacznikSSERA;

        /**
         * WYKAZ UDZIAŁÓW W SPÓŁKACH
         * 
         * Gets the value of the zalacznikSSEA property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the zalacznikSSEA property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getZalacznikSSEA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ZalacznikSSEA }
         * </p>
         * 
         * 
         * @return
         *     The value of the zalacznikSSEA property.
         */
        public List<ZalacznikSSEA> getZalacznikSSEA() {
            if (zalacznikSSEA == null) {
                zalacznikSSEA = new ArrayList<>();
            }
            return this.zalacznikSSEA;
        }

        /**
         * ROZLICZENIE ZDYSKONTOWANEJ WARTOŚCI UDZIELONEJ POMOCY PUBLICZNEJ I KOSZTÓW KWALIFIKUJĄCYCH SIĘ DO OBJĘCIA TĄ POMOCĄ
         * 
         * Gets the value of the zalacznikSSERA property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the zalacznikSSERA property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getZalacznikSSERA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ZalacznikSSERA }
         * </p>
         * 
         * 
         * @return
         *     The value of the zalacznikSSERA property.
         */
        public List<ZalacznikSSERA> getZalacznikSSERA() {
            if (zalacznikSSERA == null) {
                zalacznikSSERA = new ArrayList<>();
            }
            return this.zalacznikSSERA;
        }

    }

}
