//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._01._12.ed.citm;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._01._12.ed.citm package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.xml.schematy.dziedzinowe.mf._2024._01._12.ed.citm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalacznikCITM }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITM }
     */
    public ZalacznikCITM createZalacznikCITM() {
        return new ZalacznikCITM();
    }

    /**
     * Create an instance of {@link TNaglowekCITM }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITM }
     */
    public TNaglowekCITM createTNaglowekCITM() {
        return new TNaglowekCITM();
    }

    /**
     * Create an instance of {@link ZalacznikCITM.PozycjeSzczegolowe }
     * 
     * @return
     *     the new instance of {@link ZalacznikCITM.PozycjeSzczegolowe }
     */
    public ZalacznikCITM.PozycjeSzczegolowe createZalacznikCITMPozycjeSzczegolowe() {
        return new ZalacznikCITM.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link TNaglowekCITM.KodFormularza }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITM.KodFormularza }
     */
    public TNaglowekCITM.KodFormularza createTNaglowekCITMKodFormularza() {
        return new TNaglowekCITM.KodFormularza();
    }

    /**
     * Create an instance of {@link TNaglowekCITM.OkresOd }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITM.OkresOd }
     */
    public TNaglowekCITM.OkresOd createTNaglowekCITMOkresOd() {
        return new TNaglowekCITM.OkresOd();
    }

    /**
     * Create an instance of {@link TNaglowekCITM.OkresDo }
     * 
     * @return
     *     the new instance of {@link TNaglowekCITM.OkresDo }
     */
    public TNaglowekCITM.OkresDo createTNaglowekCITMOkresDo() {
        return new TNaglowekCITM.OkresDo();
    }

}
