//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/ORDZU/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._09._13.ed.ordzu;
