//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.12 at 11:04:52 AM CET 
//


package pl.gov.crd.wzor._2021._11._29._11089;

import pl.janksiegowy.backend.entity.dto.ContactDto;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Zestaw danych identyfikacyjnych oraz danych adresowych nabywcy i podmiot�w trzecich
 * 
 * &lt;p&gt;Java class for TPodmiot complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="TPodmiot"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;element name="NIP" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TNrNIP"/&amp;gt;
 *           &amp;lt;element name="NrID" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TNrIdentyfikacjiPodatkowej"/&amp;gt;
 *           &amp;lt;element name="BrakID" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TWybor1"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *         &amp;lt;sequence minOccurs="0"&amp;gt;
 *           &amp;lt;choice&amp;gt;
 *             &amp;lt;sequence&amp;gt;
 *               &amp;lt;element name="ImiePierwsze" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TImie"/&amp;gt;
 *               &amp;lt;element name="Nazwisko" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/09/eD/DefinicjeTypy/}TNazwisko"/&amp;gt;
 *             &amp;lt;/sequence&amp;gt;
 *             &amp;lt;element name="PelnaNazwa" type="{http://crd.gov.pl/wzor/2021/11/29/11089/}TZnakowy"/&amp;gt;
 *           &amp;lt;/choice&amp;gt;
 *           &amp;lt;element name="NazwaHandlowa" type="{http://crd.gov.pl/wzor/2021/11/29/11089/}TZnakowy" minOccurs="0"/&amp;gt;
 *         &amp;lt;/sequence&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType( XmlAccessType.PROPERTY)
@XmlType(name = "TPodmiot", propOrder = {
    "NIP",
    "nrID",
    "brakID",
    "imiePierwsze",
    "nazwisko",
    "pelnaNazwa",
    "nazwaHandlowa"
})
public abstract class TPodmiot {
    private final ContactDto entity;

    public TPodmiot( ContactDto entity) {
        this.entity= entity;
    }

    /**
     * Gets the value of the nip property.
     */
    @XmlElement( name= "NIP")
    public abstract String getNIP();

    /**
     * Gets the value of the nrID property.
     */
    @XmlElement( name= "NrID")
    public abstract String getNrID();

    /**
     * Gets the value of the brakID property.
     */
    @XmlElement( name= "BrakID")
    public abstract Integer getBrakID();

    /**
     * Gets the value of the imiePierwsze property.
     */
    @XmlElement( name= "ImiePierwsze")
    public abstract String getImiePierwsze();

    /**
     * Gets the value of the nazwisko property.
     */
    @XmlElement( name= "Nazwisko")
    public abstract String getNazwisko();

    /**
     * Gets the value of the pelnaNazwa property.
     */
    @XmlElement( name= "PelnaNazwa")
    public abstract String getPelnaNazwa();

    /**
     * Gets the value of the nazwaHandlowa property.
     */
    @XmlElement( name= "NazwaHandlowa")
    public String getNazwaHandlowa() { // not used
        return null;
    }

}
