//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.wzor._2021._12._27._11149;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Oznaczenie dowodu nabycia
 * 
 * <p>Java class for TDowoduZakupu</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="TDowoduZakupu">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="MK"/>
 *     <enumeration value="VAT_RR"/>
 *     <enumeration value="WEW"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "TDowoduZakupu")
@XmlEnum
public enum TDowoduZakupu {

    MK,
    VAT_RR,
    WEW;

    public String value() {
        return name();
    }

    public static TDowoduZakupu fromValue(String v) {
        return valueOf(v);
    }

}
