//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.23 at 09:07:15 PM CET 
//


package pl.gov.crd.wzor._2021._12._27._11149;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for TKodFormularzaVATK.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="TKodFormularzaVATK"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="VAT-7K"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "TKodFormularzaVATK")
@XmlEnum
public enum TKodFormularzaVATK {

    @XmlEnumValue("VAT-7K")
    VAT_7_K("VAT-7K");
    private final String value;

    TKodFormularzaVATK(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TKodFormularzaVATK fromValue(String v) {
        for (TKodFormularzaVATK c: TKodFormularzaVATK.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
