//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.wzor._2021._12._27._11149;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Nagłówek JPK_VAT
 * 
 * <p>Java class for TNaglowek complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TNaglowek">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="KodFormularza">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://crd.gov.pl/wzor/2021/12/27/11149/>TKodFormularza">
 *                 <attribute name="kodSystemowy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="JPK_V7K (2)" />
 *                 <attribute name="wersjaSchemy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1-0E" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="WariantFormularza">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               <enumeration value="2"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="DataWytworzeniaJPK" type="{http://crd.gov.pl/wzor/2021/12/27/11149/}TDataCzas"/>
 *         <element name="NazwaSystemu" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               <minLength value="1"/>
 *               <maxLength value="240"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="CelZlozenia">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/>TCelZlozenia">
 *                 <attribute name="poz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="P_7" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="KodUrzedu" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TKodUS"/>
 *         <element name="Rok">
 *           <simpleType>
 *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TRok">
 *               <minInclusive value="2022"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Miesiac" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TMiesiac"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TNaglowek", propOrder = {
    "kodFormularza",
    "wariantFormularza",
    "dataWytworzeniaJPK",
    "nazwaSystemu",
    "celZlozenia",
    "kodUrzedu",
    "rok",
    "miesiac"
})
@XmlSeeAlso({
    Ewidencja_JPK_V7K_2_v1_0e.Naglowek.class
})
public class TNaglowek {

    @XmlElement(name = "KodFormularza", required = true)
    protected KodFormularza kodFormularza;
    @XmlElement(name = "WariantFormularza")
    protected byte wariantFormularza;
    /**
     * Data i czas sporządzenia JPK_VAT
     * 
     */
    @XmlElement(name = "DataWytworzeniaJPK", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataWytworzeniaJPK;
    /**
     * Nazwa systemu, z którego pochodzą dane
     * 
     */
    @XmlElement(name = "NazwaSystemu")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nazwaSystemu;
    @XmlElement(name = "CelZlozenia", required = true)
    protected CelZlozenia celZlozenia;
    @XmlElement(name = "KodUrzedu", required = true)
    protected String kodUrzedu;
    @XmlElement(name = "Rok", required = true)
    protected XMLGregorianCalendar rok;
    @XmlElement(name = "Miesiac")
    protected byte miesiac;

    /**
     * Gets the value of the kodFormularza property.
     * 
     * @return
     *     possible object is
     *     {@link KodFormularza }
     *     
     */
    public KodFormularza getKodFormularza() {
        return kodFormularza;
    }

    /**
     * Sets the value of the kodFormularza property.
     * 
     * @param value
     *     allowed object is
     *     {@link KodFormularza }
     *     
     */
    public void setKodFormularza( KodFormularza value) {
        this.kodFormularza = value;
    }

    /**
     * Gets the value of the wariantFormularza property.
     * 
     */
    public byte getWariantFormularza() {
        return wariantFormularza;
    }

    /**
     * Sets the value of the wariantFormularza property.
     * 
     */
    public void setWariantFormularza(byte value) {
        this.wariantFormularza = value;
    }

    /**
     * Data i czas sporządzenia JPK_VAT
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataWytworzeniaJPK() {
        return dataWytworzeniaJPK;
    }

    /**
     * Sets the value of the dataWytworzeniaJPK property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getDataWytworzeniaJPK()
     */
    public void setDataWytworzeniaJPK(XMLGregorianCalendar value) {
        this.dataWytworzeniaJPK = value;
    }

    /**
     * Nazwa systemu, z którego pochodzą dane
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwaSystemu() {
        return nazwaSystemu;
    }

    /**
     * Sets the value of the nazwaSystemu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNazwaSystemu()
     */
    public void setNazwaSystemu(String value) {
        this.nazwaSystemu = value;
    }

    /**
     * Gets the value of the celZlozenia property.
     * 
     * @return
     *     possible object is
     *     {@link CelZlozenia }
     *     
     */
    public CelZlozenia getCelZlozenia() {
        return celZlozenia;
    }

    /**
     * Sets the value of the celZlozenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link CelZlozenia }
     *     
     */
    public void setCelZlozenia( CelZlozenia value) {
        this.celZlozenia = value;
    }

    /**
     * Gets the value of the kodUrzedu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodUrzedu() {
        return kodUrzedu;
    }

    /**
     * Sets the value of the kodUrzedu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodUrzedu(String value) {
        this.kodUrzedu = value;
    }

    /**
     * Gets the value of the rok property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRok() {
        return rok;
    }

    /**
     * Sets the value of the rok property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRok(XMLGregorianCalendar value) {
        this.rok = value;
    }

    /**
     * Gets the value of the miesiac property.
     * 
     */
    public byte getMiesiac() {
        return miesiac;
    }

    /**
     * Sets the value of the miesiac property.
     * 
     */
    public void setMiesiac(byte value) {
        this.miesiac = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/>TCelZlozenia">
     *       <attribute name="poz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="P_7" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CelZlozenia {

        /**
         * Określa, czy to jest złożenie, czy korekta dokumentu
         * 
         */
        @XmlValue
        protected byte value;
        @XmlAttribute(name = "poz", required = true)
        protected String poz;

        /**
         * Określa, czy to jest złożenie, czy korekta dokumentu
         * 
         */
        public byte getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(byte value) {
            this.value = value;
        }

        /**
         * Gets the value of the poz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoz() {
            if (poz == null) {
                return "P_7";
            } else {
                return poz;
            }
        }

        /**
         * Sets the value of the poz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoz(String value) {
            this.poz = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://crd.gov.pl/wzor/2021/12/27/11149/>TKodFormularza">
     *       <attribute name="kodSystemowy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="JPK_V7K (2)" />
     *       <attribute name="wersjaSchemy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1-0E" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class KodFormularza {

        /**
         * Symbol wzoru formularza
         * 
         */
        @XmlValue
        protected TKodFormularza value;
        @XmlAttribute(name = "kodSystemowy", required = true)
        protected String kodSystemowy;
        @XmlAttribute(name = "wersjaSchemy", required = true)
        protected String wersjaSchemy;

        /**
         * Symbol wzoru formularza
         * 
         * @return
         *     possible object is
         *     {@link TKodFormularza }
         *     
         */
        public TKodFormularza getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link TKodFormularza }
         *     
         * @see #getValue()
         */
        public void setValue(TKodFormularza value) {
            this.value = value;
        }

        /**
         * Gets the value of the kodSystemowy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKodSystemowy() {
            if (kodSystemowy == null) {
                return "JPK_V7K (2)";
            } else {
                return kodSystemowy;
            }
        }

        /**
         * Sets the value of the kodSystemowy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKodSystemowy(String value) {
            this.kodSystemowy = value;
        }

        /**
         * Gets the value of the wersjaSchemy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWersjaSchemy() {
            if (wersjaSchemy == null) {
                return "1-0E";
            } else {
                return wersjaSchemy;
            }
        }

        /**
         * Sets the value of the wersjaSchemy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWersjaSchemy(String value) {
            this.wersjaSchemy = value;
        }

    }

}
