//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.wzor._2021._12._27._11149;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import pl.gov.crd.xml.schematy.dziedzinowe.mf._2021._06._08.ed.definicjetypy.TIdentyfikatorOsobyFizycznej2;


/**
 * Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP
 * 
 * <p>Java class for TPodmiotDowolnyBezAdresu complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TPodmiotDowolnyBezAdresu">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="OsobaFizyczna">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TIdentyfikatorOsobyFizycznej2">
 *                 <sequence>
 *                   <element name="Email" type="{http://crd.gov.pl/wzor/2021/12/27/11149/}TAdresEmail"/>
 *                   <element name="Telefon" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TZnakowy">
 *                         <maxLength value="16"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="OsobaNiefizyczna">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://crd.gov.pl/wzor/2021/12/27/11149/}TIdentyfikatorOsobyNiefizycznej">
 *                 <sequence>
 *                   <element name="Email" type="{http://crd.gov.pl/wzor/2021/12/27/11149/}TAdresEmail"/>
 *                   <element name="Telefon" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TZnakowy">
 *                         <maxLength value="16"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPodmiotDowolnyBezAdresu", propOrder = {
    "osobaFizyczna",
    "osobaNiefizyczna"
})
@XmlSeeAlso({
    Ewidencja_JPK_V7K_2_v1_0e.Podmiot1 .class
})
public class TPodmiotDowolnyBezAdresu {

    @XmlElement(name = "OsobaFizyczna")
    protected OsobaFizyczna osobaFizyczna;
    @XmlElement(name = "OsobaNiefizyczna")
    protected OsobaNiefizyczna osobaNiefizyczna;

    /**
     * Gets the value of the osobaFizyczna property.
     * 
     * @return
     *     possible object is
     *     {@link OsobaFizyczna }
     *     
     */
    public OsobaFizyczna getOsobaFizyczna() {
        return osobaFizyczna;
    }

    /**
     * Sets the value of the osobaFizyczna property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsobaFizyczna }
     *     
     */
    public void setOsobaFizyczna( OsobaFizyczna value) {
        this.osobaFizyczna = value;
    }

    /**
     * Gets the value of the osobaNiefizyczna property.
     * 
     * @return
     *     possible object is
     *     {@link OsobaNiefizyczna }
     *     
     */
    public OsobaNiefizyczna getOsobaNiefizyczna() {
        return osobaNiefizyczna;
    }

    /**
     * Sets the value of the osobaNiefizyczna property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsobaNiefizyczna }
     *     
     */
    public void setOsobaNiefizyczna( OsobaNiefizyczna value) {
        this.osobaNiefizyczna = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TIdentyfikatorOsobyFizycznej2">
     *       <sequence>
     *         <element name="Email" type="{http://crd.gov.pl/wzor/2021/12/27/11149/}TAdresEmail"/>
     *         <element name="Telefon" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TZnakowy">
     *               <maxLength value="16"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "email",
        "telefon"
    })
    public static class OsobaFizyczna
        extends TIdentyfikatorOsobyFizycznej2
    {

        @XmlElement(name = "Email", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String email;
        /**
         * Numer telefonu kontaktowego
         * 
         */
        @XmlElement(name = "Telefon")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String telefon;

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Numer telefonu kontaktowego
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefon() {
            return telefon;
        }

        /**
         * Sets the value of the telefon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getTelefon()
         */
        public void setTelefon(String value) {
            this.telefon = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://crd.gov.pl/wzor/2021/12/27/11149/}TIdentyfikatorOsobyNiefizycznej">
     *       <sequence>
     *         <element name="Email" type="{http://crd.gov.pl/wzor/2021/12/27/11149/}TAdresEmail"/>
     *         <element name="Telefon" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TZnakowy">
     *               <maxLength value="16"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "email",
        "telefon"
    })
    public static class OsobaNiefizyczna
        extends TIdentyfikatorOsobyNiefizycznej
    {

        @XmlElement(name = "Email", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String email;
        /**
         * Numer telefonu kontaktowego
         * 
         */
        @XmlElement(name = "Telefon")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String telefon;

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Numer telefonu kontaktowego
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefon() {
            return telefon;
        }

        /**
         * Sets the value of the telefon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getTelefon()
         */
        public void setTelefon(String value) {
            this.telefon = value;
        }

    }

}
