//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.wzor._2024._02._08._13272;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.wzor._2024._02._08._13272 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.wzor._2024._02._08._13272
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Deklaracja_CIT_8_33_v2_0e }
     * 
     * @return
     *     the new instance of {@link Deklaracja_CIT_8_33_v2_0e }
     */
    public Deklaracja_CIT_8_33_v2_0e createDeklaracja() {
        return new Deklaracja_CIT_8_33_v2_0e();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna2 }
     * 
     * @return
     *     the new instance of {@link TOsobaNiefizyczna2 }
     */
    public TOsobaNiefizyczna2 createTOsobaNiefizyczna2() {
        return new TOsobaNiefizyczna2();
    }

    /**
     * Create an instance of {@link TNaglowek }
     * 
     * @return
     *     the new instance of {@link TNaglowek }
     */
    public TNaglowek createTNaglowek() {
        return new TNaglowek();
    }

    /**
     * Create an instance of {@link Deklaracja_CIT_8_33_v2_0e.Podmiot1 }
     * 
     * @return
     *     the new instance of {@link Deklaracja_CIT_8_33_v2_0e.Podmiot1 }
     */
    public Deklaracja_CIT_8_33_v2_0e.Podmiot1 createDeklaracjaPodmiot1() {
        return new Deklaracja_CIT_8_33_v2_0e.Podmiot1();
    }

    /**
     * Create an instance of {@link Deklaracja_CIT_8_33_v2_0e.PozycjeSzczegolowe }
     * 
     * @return
     *     the new instance of {@link Deklaracja_CIT_8_33_v2_0e.PozycjeSzczegolowe }
     */
    public Deklaracja_CIT_8_33_v2_0e.PozycjeSzczegolowe createDeklaracjaPozycjeSzczegolowe() {
        return new Deklaracja_CIT_8_33_v2_0e.PozycjeSzczegolowe();
    }

    /**
     * Create an instance of {@link Deklaracja_CIT_8_33_v2_0e.Zalaczniki }
     * 
     * @return
     *     the new instance of {@link Deklaracja_CIT_8_33_v2_0e.Zalaczniki }
     */
    public Deklaracja_CIT_8_33_v2_0e.Zalaczniki createDeklaracjaZalaczniki() {
        return new Deklaracja_CIT_8_33_v2_0e.Zalaczniki();
    }

    /**
     * Create an instance of {@link TAdres1 }
     * 
     * @return
     *     the new instance of {@link TAdres1 }
     */
    public TAdres1 createTAdres1() {
        return new TAdres1();
    }

    /**
     * Create an instance of {@link TAdresPolski1 }
     * 
     * @return
     *     the new instance of {@link TAdresPolski1 }
     */
    public TAdresPolski1 createTAdresPolski1() {
        return new TAdresPolski1();
    }

    /**
     * Create an instance of {@link TAdresZagraniczny }
     * 
     * @return
     *     the new instance of {@link TAdresZagraniczny }
     */
    public TAdresZagraniczny createTAdresZagraniczny() {
        return new TAdresZagraniczny();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna2 .AdresSiedziby }
     * 
     * @return
     *     the new instance of {@link TOsobaNiefizyczna2 .AdresSiedziby }
     */
    public TOsobaNiefizyczna2 .AdresSiedziby createTOsobaNiefizyczna2AdresSiedziby() {
        return new TOsobaNiefizyczna2 .AdresSiedziby();
    }

    /**
     * Create an instance of {@link TNaglowek.KodFormularza }
     * 
     * @return
     *     the new instance of {@link TNaglowek.KodFormularza }
     */
    public TNaglowek.KodFormularza createTNaglowekKodFormularza() {
        return new TNaglowek.KodFormularza();
    }

    /**
     * Create an instance of {@link TNaglowek.CelZlozenia }
     * 
     * @return
     *     the new instance of {@link TNaglowek.CelZlozenia }
     */
    public TNaglowek.CelZlozenia createTNaglowekCelZlozenia() {
        return new TNaglowek.CelZlozenia();
    }

    /**
     * Create an instance of {@link TNaglowek.OkresOd }
     * 
     * @return
     *     the new instance of {@link TNaglowek.OkresOd }
     */
    public TNaglowek.OkresOd createTNaglowekOkresOd() {
        return new TNaglowek.OkresOd();
    }

    /**
     * Create an instance of {@link TNaglowek.OkresDo }
     * 
     * @return
     *     the new instance of {@link TNaglowek.OkresDo }
     */
    public TNaglowek.OkresDo createTNaglowekOkresDo() {
        return new TNaglowek.OkresDo();
    }

}
