//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

@XmlSchema(
    namespace= "http://crd.gov.pl/wzor/2024/02/08/13272/",
    elementFormDefault= XmlNsForm.QUALIFIED,
    xmlns= {
        @XmlNs( prefix= "", namespaceURI= "http://crd.gov.pl/wzor/2024/02/08/13272/"),
        @XmlNs( prefix= "etd", namespaceURI= "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")
    }
)
package pl.gov.crd.wzor._2024._02._08._13272;

import jakarta.xml.bind.annotation.XmlSchema;
import jakarta.xml.bind.annotation.XmlNsForm;
import jakarta.xml.bind.annotation.XmlNs;