//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.wzor._2024._02._08._13272;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Nagłówek deklaracji
 * 
 * <p>Java class for TNaglowek complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TNaglowek">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="KodFormularza">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://crd.gov.pl/wzor/2024/02/08/13272/>TKodFormularza">
 *                 <attribute name="kodSystemowy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="CIT-8 (33)" />
 *                 <attribute name="kodPodatku" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="CIT" />
 *                 <attribute name="rodzajZobowiazania" use="required" type="{http://www.w3.org/2001/XMLSchema}token" fixed="Z" />
 *                 <attribute name="wersjaSchemy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="2-0E" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="WariantFormularza">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               <enumeration value="33"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="CelZlozenia">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/>TCelZlozenia">
 *                 <attribute name="poz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="P_7" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="OkresOd">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://crd.gov.pl/wzor/2024/02/08/13272/>TLDataP">
 *                 <attribute name="poz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="P_4" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="OkresDo">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://crd.gov.pl/wzor/2024/02/08/13272/>TLDataP">
 *                 <attribute name="poz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="P_5" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="KodUrzedu" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/KodyUrzedowSkarbowych/}TKodUS"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TNaglowek", propOrder = {
    "kodFormularza",
    "wariantFormularza",
    "celZlozenia",
    "okresOd",
    "okresDo",
    "kodUrzedu"
})
public class TNaglowek {

    @XmlElement(name = "KodFormularza", required = true)
    protected KodFormularza kodFormularza;
    @XmlElement(name = "WariantFormularza")
    protected byte wariantFormularza;
    @XmlElement(name = "CelZlozenia", required = true)
    protected CelZlozenia celZlozenia;
    @XmlElement(name = "OkresOd", required = true)
    protected OkresOd okresOd;
    @XmlElement(name = "OkresDo", required = true)
    protected OkresDo okresDo;
    @XmlElement(name = "KodUrzedu", required = true)
    protected String kodUrzedu;

    /**
     * Gets the value of the kodFormularza property.
     * 
     * @return
     *     possible object is
     *     {@link KodFormularza }
     *     
     */
    public KodFormularza getKodFormularza() {
        return kodFormularza;
    }

    /**
     * Sets the value of the kodFormularza property.
     * 
     * @param value
     *     allowed object is
     *     {@link KodFormularza }
     *     
     */
    public void setKodFormularza( KodFormularza value) {
        this.kodFormularza = value;
    }

    /**
     * Gets the value of the wariantFormularza property.
     * 
     */
    public byte getWariantFormularza() {
        return wariantFormularza;
    }

    /**
     * Sets the value of the wariantFormularza property.
     * 
     */
    public void setWariantFormularza(byte value) {
        this.wariantFormularza = value;
    }

    /**
     * Gets the value of the celZlozenia property.
     * 
     * @return
     *     possible object is
     *     {@link CelZlozenia }
     *     
     */
    public CelZlozenia getCelZlozenia() {
        return celZlozenia;
    }

    /**
     * Sets the value of the celZlozenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link CelZlozenia }
     *     
     */
    public void setCelZlozenia( CelZlozenia value) {
        this.celZlozenia = value;
    }

    /**
     * Gets the value of the okresOd property.
     * 
     * @return
     *     possible object is
     *     {@link OkresOd }
     *     
     */
    public OkresOd getOkresOd() {
        return okresOd;
    }

    /**
     * Sets the value of the okresOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OkresOd }
     *     
     */
    public void setOkresOd( OkresOd value) {
        this.okresOd = value;
    }

    /**
     * Gets the value of the okresDo property.
     * 
     * @return
     *     possible object is
     *     {@link OkresDo }
     *     
     */
    public OkresDo getOkresDo() {
        return okresDo;
    }

    /**
     * Sets the value of the okresDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OkresDo }
     *     
     */
    public void setOkresDo( OkresDo value) {
        this.okresDo = value;
    }

    /**
     * Gets the value of the kodUrzedu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodUrzedu() {
        return kodUrzedu;
    }

    /**
     * Sets the value of the kodUrzedu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodUrzedu(String value) {
        this.kodUrzedu = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/>TCelZlozenia">
     *       <attribute name="poz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="P_7" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CelZlozenia {

        /**
         * Określa, czy to jest złożenie, czy korekta dokumentu
         * 
         */
        @XmlValue
        protected byte value;
        @XmlAttribute(name = "poz", required = true)
        protected String poz;

        /**
         * Określa, czy to jest złożenie, czy korekta dokumentu
         * 
         */
        public byte getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(byte value) {
            this.value = value;
        }

        /**
         * Gets the value of the poz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoz() {
            if (poz == null) {
                return "P_7";
            } else {
                return poz;
            }
        }

        /**
         * Sets the value of the poz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoz(String value) {
            this.poz = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://crd.gov.pl/wzor/2024/02/08/13272/>TKodFormularza">
     *       <attribute name="kodSystemowy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="CIT-8 (33)" />
     *       <attribute name="kodPodatku" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="CIT" />
     *       <attribute name="rodzajZobowiazania" use="required" type="{http://www.w3.org/2001/XMLSchema}token" fixed="Z" />
     *       <attribute name="wersjaSchemy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="2-0E" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class KodFormularza {

        /**
         * Symbol wzoru formularza
         * 
         */
        @XmlValue
        protected TKodFormularza value;
        @XmlAttribute(name = "kodSystemowy", required = true)
        protected String kodSystemowy;
        @XmlAttribute(name = "kodPodatku", required = true)
        protected String kodPodatku;
        @XmlAttribute(name = "rodzajZobowiazania", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String rodzajZobowiazania;
        @XmlAttribute(name = "wersjaSchemy", required = true)
        protected String wersjaSchemy;

        /**
         * Symbol wzoru formularza
         * 
         * @return
         *     possible object is
         *     {@link TKodFormularza }
         *     
         */
        public TKodFormularza getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link TKodFormularza }
         *     
         * @see #getValue()
         */
        public void setValue(TKodFormularza value) {
            this.value = value;
        }

        /**
         * Gets the value of the kodSystemowy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKodSystemowy() {
            if (kodSystemowy == null) {
                return "CIT-8 (33)";
            } else {
                return kodSystemowy;
            }
        }

        /**
         * Sets the value of the kodSystemowy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKodSystemowy(String value) {
            this.kodSystemowy = value;
        }

        /**
         * Gets the value of the kodPodatku property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKodPodatku() {
            if (kodPodatku == null) {
                return "CIT";
            } else {
                return kodPodatku;
            }
        }

        /**
         * Sets the value of the kodPodatku property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKodPodatku(String value) {
            this.kodPodatku = value;
        }

        /**
         * Gets the value of the rodzajZobowiazania property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRodzajZobowiazania() {
            if (rodzajZobowiazania == null) {
                return "Z";
            } else {
                return rodzajZobowiazania;
            }
        }

        /**
         * Sets the value of the rodzajZobowiazania property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRodzajZobowiazania(String value) {
            this.rodzajZobowiazania = value;
        }

        /**
         * Gets the value of the wersjaSchemy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWersjaSchemy() {
            if (wersjaSchemy == null) {
                return "2-0E";
            } else {
                return wersjaSchemy;
            }
        }

        /**
         * Sets the value of the wersjaSchemy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWersjaSchemy(String value) {
            this.wersjaSchemy = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://crd.gov.pl/wzor/2024/02/08/13272/>TLDataP">
     *       <attribute name="poz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="P_5" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OkresDo {

        /**
         * Ograniczenie dla daty początku okresu
         * 
         */
        @XmlValue
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "poz", required = true)
        protected String poz;

        /**
         * Ograniczenie dla daty początku okresu
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getValue()
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the poz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoz() {
            if (poz == null) {
                return "P_5";
            } else {
                return poz;
            }
        }

        /**
         * Sets the value of the poz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoz(String value) {
            this.poz = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://crd.gov.pl/wzor/2024/02/08/13272/>TLDataP">
     *       <attribute name="poz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="P_4" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OkresOd {

        /**
         * Ograniczenie dla daty początku okresu
         * 
         */
        @XmlValue
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "poz", required = true)
        protected String poz;

        /**
         * Ograniczenie dla daty początku okresu
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getValue()
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the poz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoz() {
            if (poz == null) {
                return "P_4";
            } else {
                return poz;
            }
        }

        /**
         * Sets the value of the poz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoz(String value) {
            this.poz = value;
        }

    }

}
