//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2021._06._08.ed.definicjetypy;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Informacje opisujące adres zagraniczny
 * 
 * <p>Java class for TAdresZagraniczny complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TAdresZagraniczny">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="KodKraju">
 *           <simpleType>
 *             <restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TKodKraju">
 *               <pattern value="P[A-KM-Z]"/>
 *               <pattern value="[A-OQ-Z][A-Z]"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="KodPocztowy" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TKodPocztowy" minOccurs="0"/>
 *         <element name="Miejscowosc" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TMiejscowosc"/>
 *         <element name="Ulica" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TUlica" minOccurs="0"/>
 *         <element name="NrDomu" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TNrBudynku" minOccurs="0"/>
 *         <element name="NrLokalu" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2021/06/08/eD/DefinicjeTypy/}TNrLokalu" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAdresZagraniczny", propOrder = {
    "kodKraju",
    "kodPocztowy",
    "miejscowosc",
    "ulica",
    "nrDomu",
    "nrLokalu"
})
public class TAdresZagraniczny {

    /**
     * Kod Kraju [Country Code]
     * 
     */
    @XmlElement(name = "KodKraju", required = true)
    protected TKodKraju kodKraju;
    /**
     * Kod pocztowy [Postal code]
     * 
     */
    @XmlElement(name = "KodPocztowy")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String kodPocztowy;
    /**
     * Nazwa miejscowości [City]
     * 
     */
    @XmlElement(name = "Miejscowosc", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String miejscowosc;
    /**
     * Nazwa ulicy [Street]
     * 
     */
    @XmlElement(name = "Ulica")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String ulica;
    /**
     * Numer budynku [Building number]
     * 
     */
    @XmlElement(name = "NrDomu")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nrDomu;
    /**
     * Numer lokalu [Flat number]
     * 
     */
    @XmlElement(name = "NrLokalu")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nrLokalu;

    /**
     * Kod Kraju [Country Code]
     * 
     * @return
     *     possible object is
     *     {@link TKodKraju }
     *     
     */
    public TKodKraju getKodKraju() {
        return kodKraju;
    }

    /**
     * Sets the value of the kodKraju property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodKraju }
     *     
     * @see #getKodKraju()
     */
    public void setKodKraju(TKodKraju value) {
        this.kodKraju = value;
    }

    /**
     * Kod pocztowy [Postal code]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodPocztowy() {
        return kodPocztowy;
    }

    /**
     * Sets the value of the kodPocztowy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getKodPocztowy()
     */
    public void setKodPocztowy(String value) {
        this.kodPocztowy = value;
    }

    /**
     * Nazwa miejscowości [City]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiejscowosc() {
        return miejscowosc;
    }

    /**
     * Sets the value of the miejscowosc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getMiejscowosc()
     */
    public void setMiejscowosc(String value) {
        this.miejscowosc = value;
    }

    /**
     * Nazwa ulicy [Street]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUlica() {
        return ulica;
    }

    /**
     * Sets the value of the ulica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUlica()
     */
    public void setUlica(String value) {
        this.ulica = value;
    }

    /**
     * Numer budynku [Building number]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrDomu() {
        return nrDomu;
    }

    /**
     * Sets the value of the nrDomu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNrDomu()
     */
    public void setNrDomu(String value) {
        this.nrDomu = value;
    }

    /**
     * Numer lokalu [Flat number]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrLokalu() {
        return nrLokalu;
    }

    /**
     * Sets the value of the nrLokalu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNrLokalu()
     */
    public void setNrLokalu(String value) {
        this.nrLokalu = value;
    }

}
